SET NOCOUNT ON;
PRINT '== column types';
SELECT ty.name, COUNT(*) FROM sys.columns c JOIN sys.types ty ON ty.user_type_id=c.user_type_id JOIN sys.tables t ON t.object_id=c.object_id GROUP BY ty.name ORDER BY 2 DESC;
PRINT '== identity';
SELECT OBJECT_SCHEMA_NAME(object_id)+'.'+OBJECT_NAME(object_id)+'.'+name FROM sys.identity_columns WHERE OBJECTPROPERTY(object_id,'IsUserTable')=1;
PRINT '== defaults';
SELECT CAST(definition AS nvarchar(4000)) COLLATE DATABASE_DEFAULT, COUNT(*) FROM sys.default_constraints GROUP BY CAST(definition AS nvarchar(4000)) COLLATE DATABASE_DEFAULT ORDER BY 2 DESC;
PRINT '== computed';
SELECT OBJECT_SCHEMA_NAME(c.object_id)+'.'+OBJECT_NAME(c.object_id)+'.'+c.name+' | '+CAST(c.is_persisted AS varchar)+' | '+CAST(c.definition AS nvarchar(4000)) COLLATE DATABASE_DEFAULT FROM sys.computed_columns c ORDER BY 1;
PRINT '== checks';
SELECT DISTINCT CAST(definition AS nvarchar(4000)) COLLATE DATABASE_DEFAULT FROM sys.check_constraints;
PRINT '== filtered idx';
SELECT DISTINCT CAST(filter_definition AS nvarchar(4000)) COLLATE DATABASE_DEFAULT FROM sys.indexes WHERE has_filter=1;
PRINT '== FK actions';
SELECT delete_referential_action_desc, update_referential_action_desc, COUNT(*) FROM sys.foreign_keys GROUP BY delete_referential_action_desc, update_referential_action_desc;
PRINT '== view idx / included / seq / odd collations';
SELECT COUNT(*) FROM sys.indexes i JOIN sys.views v ON v.object_id=i.object_id;
SELECT COUNT(*) FROM sys.index_columns WHERE is_included_column=1;
SELECT COUNT(*) FROM sys.sequences;
SELECT COUNT(*) FROM sys.columns c JOIN sys.tables t ON t.object_id=c.object_id WHERE c.collation_name IS NOT NULL AND c.collation_name<>'SQL_Latin1_General_CP1_CI_AS';
