-- Generated by PgMigrator from the SQL Server catalog. Tables, columns, defaults, computed columns, primary keys.
CREATE EXTENSION IF NOT EXISTS citext;
CREATE SCHEMA IF NOT EXISTS "_template";
CREATE SCHEMA IF NOT EXISTS "demorecruitment";
CREATE SCHEMA IF NOT EXISTS "platform";

CREATE TABLE "_template"."AuditLogs" (
    "Id" uuid CONSTRAINT "DF_T_Aud_Id" DEFAULT gen_random_uuid() NOT NULL,
    "ActorId" uuid,
    "ActorType" smallint NOT NULL,
    "EventType" citext NOT NULL,
    "EntityType" citext,
    "EntityId" uuid,
    "OldValueJson" citext,
    "NewValueJson" citext,
    "IPAddress" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Aud_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_AuditLogs" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Branches" (
    "Id" uuid CONSTRAINT "DF_T_Br_Id" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "City" citext,
    "Address" citext,
    "IsActive" boolean CONSTRAINT "DF_T_Br_Active" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Br_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_Branches" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Campaigns" (
    "Id" uuid CONSTRAINT "DF_T_Camp_Id" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "Source" smallint NOT NULL,
    "Status" smallint CONSTRAINT "DF_T_Camp_Status" DEFAULT 1 NOT NULL,
    "BudgetEGP" numeric(18,2),
    "SpendEGP" numeric(18,2),
    "FacebookCampaignId" citext,
    "FacebookAdSetId" citext,
    "FacebookAdId" citext,
    "UtmSource" citext,
    "UtmMedium" citext,
    "UtmCampaign" citext,
    "UtmContent" citext,
    "UtmTerm" citext,
    "StartDate" date,
    "EndDate" date,
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Camp_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_T_Campaigns" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."CandidateActivities" (
    "Id" uuid CONSTRAINT "DF_T_CA_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "ActivityType" smallint NOT NULL,
    "Description" citext,
    "Details" citext,
    "CreatedById" uuid,
    "CreatedByName" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_CA_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_CandidateActivities" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Candidates" (
    "Id" uuid CONSTRAINT "DF_T_Cand_Id" DEFAULT gen_random_uuid() NOT NULL,
    "BranchId" uuid NOT NULL,
    "AssignedSalesId" uuid NOT NULL,
    "JobPackageId" uuid NOT NULL,
    "RegisteredById" uuid NOT NULL,
    "FullName" citext NOT NULL,
    "Phone" citext NOT NULL,
    "NationalId" citext,
    "Age" integer,
    "City" citext,
    "Notes" citext,
    "Status" smallint CONSTRAINT "DF_T_Cand_Status" DEFAULT 1 NOT NULL,
    "TotalPaidEGP" numeric(18,2) CONSTRAINT "DF_T_Cand_Paid" DEFAULT 0 NOT NULL,
    "IsCompleted" boolean CONSTRAINT "DF_T_Cand_Comp" DEFAULT false NOT NULL,
    "CompletedAt" timestamp(0) without time zone,
    "IsProfileComplete" boolean CONSTRAINT "DF_T_Cand_Prof" DEFAULT false NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Cand_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    "CurrentPackageStageId" uuid,
    "PassportNumber" citext,
    "PassportExpiry" date,
    "VisaNumber" citext,
    "VisaExpiry" date,
    "CompanyId" uuid,
    "FlightDate" timestamp(0) without time zone,
    CONSTRAINT "PK_T_Candidates" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."CandidateStageHistory" (
    "Id" uuid CONSTRAINT "DF_T_CSH_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "FromStage" smallint,
    "ToStage" smallint NOT NULL,
    "ChangedById" uuid NOT NULL,
    "IsOverride" boolean CONSTRAINT "DF_T_CSH_Ov" DEFAULT false NOT NULL,
    "OverrideReason" citext,
    "MeetingOutcome" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_CSH_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "FromStageId" uuid,
    "ToStageId" uuid,
    "Notes" citext,
    CONSTRAINT "PK_T_CSH" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Commissions" (
    "Id" uuid CONSTRAINT "DF_T_Com_Id" DEFAULT gen_random_uuid() NOT NULL,
    "SalesUserId" uuid NOT NULL,
    "CandidateId" uuid NOT NULL,
    "CommissionMonth" date NOT NULL,
    "AmountEGP" numeric(18,2) NOT NULL,
    "DealsThisMonth" integer NOT NULL,
    "Status" smallint CONSTRAINT "DF_T_Com_St" DEFAULT 1 NOT NULL,
    "ApprovedById" uuid,
    "ApprovedAt" timestamp(0) without time zone,
    "PaidById" uuid,
    "PaidAt" timestamp(0) without time zone,
    "ReversedReason" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Com_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_Commissions" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."CommissionTiers" (
    "Id" uuid CONSTRAINT "DF__CommissionTi__Id__0C50D423" DEFAULT gen_random_uuid() NOT NULL,
    "MinDeals" integer NOT NULL,
    "MaxDeals" integer,
    "AmountPerDeal" numeric(18,2) NOT NULL,
    "IsActive" boolean CONSTRAINT "DF__Commissio__IsAct__0D44F85C" DEFAULT true NOT NULL,
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__Commissio__Creat__0B5CAFEA" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_T_CommissionTiers" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Companies" (
    "Id" uuid CONSTRAINT "DF__Companies__Id__7FEAFD3E" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "Country" citext NOT NULL,
    "City" citext,
    "ContactPhone" citext,
    "ContactEmail" citext,
    "ContractStartDate" date,
    "Notes" citext,
    "IsActive" boolean CONSTRAINT "DF__Companies__IsAct__00DF2177" DEFAULT true NOT NULL,
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__Companies__Creat__01D345B0" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_T_Companies" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."CompanyJobs" (
    "Id" uuid CONSTRAINT "DF__CompanyJobs__Id__078C1F06" DEFAULT gen_random_uuid() NOT NULL,
    "CompanyId" uuid NOT NULL,
    "JobTitle" citext NOT NULL,
    "RequestedCount" integer CONSTRAINT "DF__CompanyJo__Reque__0880433F" DEFAULT 1 NOT NULL,
    "Notes" citext,
    "IsActive" boolean CONSTRAINT "DF__CompanyJo__IsAct__09746778" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__CompanyJo__Creat__0A688BB1" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_CompanyJobs" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."ContractUploads" (
    "Id" uuid CONSTRAINT "DF__ContractUplo__Id__318258D2" DEFAULT gen_random_uuid() NOT NULL,
    "UploadedById" uuid NOT NULL,
    "FileName" citext NOT NULL,
    "FileKey" citext NOT NULL,
    "ExtractedPassportNo" citext,
    "ExtractedEmployerName" citext,
    "ExtractedTransactionNo" citext,
    "MatchStatus" smallint CONSTRAINT "DF__ContractU__Match__32767D0B" DEFAULT 0 NOT NULL,
    "MatchedCandidateId" uuid,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__ContractU__Creat__336AA144" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_ContractUploads" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Documents" (
    "Id" uuid CONSTRAINT "DF_T_Doc_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "UploadedById" uuid NOT NULL,
    "DocumentType" smallint NOT NULL,
    "FileName" citext NOT NULL,
    "S3Key" citext NOT NULL,
    "FileSizeBytes" integer NOT NULL,
    "MimeType" citext NOT NULL,
    "UploadedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Doc_UpAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_Documents" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."FollowUpReminders" (
    "Id" uuid CONSTRAINT "DF_T_FUR_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "ActivityId" uuid,
    "AssignedToId" uuid NOT NULL,
    "CreatedById" uuid NOT NULL,
    "ReminderDate" date NOT NULL,
    "Status" smallint CONSTRAINT "DF_T_FUR_Status" DEFAULT 1 NOT NULL,
    "SnoozedUntil" date,
    "SnoozeCount" integer CONSTRAINT "DF_T_FUR_Snooze" DEFAULT 0 NOT NULL,
    "NotificationId" uuid,
    "DismissedAt" timestamp(0) without time zone,
    "DismissedById" uuid,
    "Notes" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_FUR_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_T_FUR" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."JobPackages" (
    "Id" uuid CONSTRAINT "DF_T_JP_Id" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "DestinationCountry" citext NOT NULL,
    "JobTitle" citext NOT NULL,
    "PriceEGP" numeric(18,2) NOT NULL,
    "Description" citext,
    "IsActive" boolean CONSTRAINT "DF_T_JP_Active" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_JP_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_JobPackages" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."LeadActivities" (
    "Id" uuid CONSTRAINT "DF_T_LA_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "ActivityType" smallint NOT NULL,
    "Description" citext,
    "Details" citext,
    "NextFollowUpDate" date,
    "ReminderId" uuid,
    "EntityId" uuid,
    "EntityType" citext,
    "CreatedById" uuid,
    "CreatedByName" citext,
    "ActorType" smallint CONSTRAINT "DF_T_LA_Actor" DEFAULT 1 NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_LA_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_LeadActivities" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."LeadCallLog" (
    "Id" uuid CONSTRAINT "DF_T_LCL_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "CalledById" uuid NOT NULL,
    "Channel" smallint NOT NULL,
    "Outcome" smallint NOT NULL,
    "Note" citext,
    "CalledAt" timestamp(0) without time zone CONSTRAINT "DF_T_LCL_At" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_LCL" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."LeadFunnelHistory" (
    "Id" uuid CONSTRAINT "DF_T_LFH_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "FromStatus" smallint,
    "ToStatus" smallint NOT NULL,
    "ChangedById" uuid NOT NULL,
    "Note" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_LFH_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_LFH" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Leads" (
    "Id" uuid CONSTRAINT "DF_T_Ld_Id" DEFAULT gen_random_uuid() NOT NULL,
    "BranchId" uuid NOT NULL,
    "AssignedSalesId" uuid,
    "CampaignId" uuid,
    "RegisteredById" uuid NOT NULL,
    "FullName" citext NOT NULL,
    "Phone" citext NOT NULL,
    "LeadSource" smallint NOT NULL,
    "Status" smallint CONSTRAINT "DF_T_Ld_Status" DEFAULT 1 NOT NULL,
    "Notes" citext,
    "InterestedJobTitle" citext,
    "InterestedCountry" citext,
    "ReferredByName" citext,
    "ReferredByPhone" citext,
    "IsConverted" boolean CONSTRAINT "DF_T_Ld_Conv" DEFAULT false NOT NULL,
    "ConvertedAt" timestamp(0) without time zone,
    "ConvertedCandidateId" uuid,
    "FacebookLeadId" citext,
    "FacebookFormId" citext,
    "UtmSource" citext,
    "UtmMedium" citext,
    "UtmCampaign" citext,
    "UtmContent" citext,
    "DuplicateOfLeadId" uuid,
    "IsDuplicate" boolean CONSTRAINT "DF_T_Ld_Dup" DEFAULT false NOT NULL,
    "LeadSequence" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "LeadCode" citext GENERATED ALWAYS AS (('LD-' || right('00000' || ("LeadSequence")::text, 5))::citext) STORED,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Ld_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    "LastContactedAt" timestamp(0) without time zone,
    "AppointmentDate" timestamp(0) without time zone,
    CONSTRAINT "PK_T_Leads" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."LeadVisits" (
    "Id" uuid CONSTRAINT "DF_T_LV_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "ReceptionUserId" uuid NOT NULL,
    "AssignedSalesUserId" uuid,
    "VisitDateTime" timestamp(0) without time zone CONSTRAINT "DF_T_LV_VDT" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "MeetingOutcome" smallint NOT NULL,
    "ConvertedCandidateId" uuid,
    "JobPackageId" uuid,
    "Notes" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_LV_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_LV" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Notifications" (
    "Id" uuid CONSTRAINT "DF_T_Not_Id" DEFAULT gen_random_uuid() NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" smallint NOT NULL,
    "Title" citext NOT NULL,
    "Body" citext,
    "EntityId" uuid,
    "IsRead" boolean CONSTRAINT "DF_T_Not_Read" DEFAULT false NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Not_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "Link" citext,
    "ReadAt" timestamp(6) without time zone,
    CONSTRAINT "PK_T_Notifications" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."PackageStages" (
    "Id" uuid CONSTRAINT "DF_T_PS_Id" DEFAULT gen_random_uuid() NOT NULL,
    "PackageId" uuid NOT NULL,
    "StageName" citext NOT NULL,
    "StageOrder" integer NOT NULL,
    "RequiredMinPaymentEGP" numeric(18,2),
    "Description" citext,
    "NotifySalesOnEnter" boolean CONSTRAINT "DF_T_PS_Notif" DEFAULT false NOT NULL,
    "IsActive" boolean CONSTRAINT "DF_T_PS_Active" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_PS_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "StageTypeId" uuid,
    "NotifyAdminOnEnter" boolean CONSTRAINT "DF_T_PS_NotifAdmin" DEFAULT false NOT NULL,
    "RequiresAdminApproval" boolean CONSTRAINT "DF_T_PS_AdminApproval" DEFAULT false NOT NULL,
    CONSTRAINT "PK_T_PackageStages" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."PassportDownloadedCandidates" (
    "Id" uuid CONSTRAINT "DF__PassportDown__Id__373B3228" DEFAULT gen_random_uuid() NOT NULL,
    "LogId" uuid NOT NULL,
    "CandidateId" uuid NOT NULL,
    "DocumentId" uuid,
    "DownloadedAt" timestamp(6) without time zone CONSTRAINT "DF__PassportD__Downl__382F5661" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_PDC" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."PassportDownloadLogs" (
    "Id" uuid CONSTRAINT "DF__PassportDown__Id__11158940" DEFAULT gen_random_uuid() NOT NULL,
    "PackageId" uuid NOT NULL,
    "DownloadedById" uuid NOT NULL,
    "DownloadedAt" timestamp(6) without time zone CONSTRAINT "DF__PassportD__Downl__1209AD79" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "PassportCount" integer NOT NULL,
    "IsNewOnly" boolean CONSTRAINT "DF__PassportD__IsNew__12FDD1B2" DEFAULT false NOT NULL,
    CONSTRAINT "PK_T_PDL" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Payments" (
    "Id" uuid CONSTRAINT "DF_T_Pay_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "RecordedById" uuid NOT NULL,
    "AmountEGP" numeric(18,2) NOT NULL,
    "PaymentDate" date NOT NULL,
    "PaymentMethod" smallint NOT NULL,
    "TransactionType" smallint NOT NULL,
    "Notes" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Pay_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_Payments" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."RefreshTokens" (
    "Id" uuid CONSTRAINT "DF_T_RT_Id" DEFAULT gen_random_uuid() NOT NULL,
    "UserId" uuid NOT NULL,
    "Token" citext NOT NULL,
    "ExpiresAt" timestamp(0) without time zone NOT NULL,
    "IsRevoked" boolean CONSTRAINT "DF_T_RT_Rev" DEFAULT false NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_RT_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_RefreshTokens" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Refunds" (
    "Id" uuid CONSTRAINT "DF_T_Ref_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "AmountEGP" numeric(18,2) NOT NULL,
    "Reason" citext NOT NULL,
    "Status" smallint CONSTRAINT "DF_T_Ref_St" DEFAULT 1 NOT NULL,
    "RequestedById" uuid NOT NULL,
    "RequestedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Ref_ReqAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "ReviewedById" uuid,
    "ReviewedAt" timestamp(0) without time zone,
    "RejectReason" citext,
    "ExecutedById" uuid,
    "ExecutedAt" timestamp(0) without time zone,
    "RefundPaymentId" uuid,
    CONSTRAINT "PK_T_Refunds" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."SalaryPayments" (
    "Id" uuid CONSTRAINT "DF__SalaryPaymen__Id__4865BE2A" DEFAULT gen_random_uuid() NOT NULL,
    "UserId" uuid NOT NULL,
    "SalaryMonth" date NOT NULL,
    "BaseSalary" numeric(18,2) NOT NULL,
    "Adjustment" numeric(18,2) CONSTRAINT "DF__SalaryPay__Adjus__4959E263" DEFAULT 0 NOT NULL,
    "AdjustmentNote" citext,
    "TotalAmount" numeric(19,2) GENERATED ALWAYS AS (("BaseSalary" + "Adjustment")) STORED,
    "Status" smallint CONSTRAINT "DF__SalaryPay__Statu__4A4E069C" DEFAULT 1 NOT NULL,
    "ApprovedById" uuid,
    "ApprovedAt" timestamp(0) without time zone,
    "PaidById" uuid,
    "PaidAt" timestamp(0) without time zone,
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__SalaryPay__Creat__4B422AD5" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_T_SalaryPayments" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."StageActionCompletions" (
    "Id" uuid CONSTRAINT "DF__StageActionC__Id__43A1090D" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "PackageStageId" uuid NOT NULL,
    "CompletedAt" timestamp(6) without time zone CONSTRAINT "DF__StageActi__Compl__44952D46" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "CompletedById" uuid NOT NULL,
    "CompletionType" smallint NOT NULL,
    "Notes" citext,
    CONSTRAINT "PK_T_SAC" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."StageApprovalRequests" (
    "Id" uuid CONSTRAINT "DF__StageApprova__Id__2AD55B43" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "FromStageId" uuid NOT NULL,
    "ToStageId" uuid NOT NULL,
    "RequestedById" uuid NOT NULL,
    "RequestedAt" timestamp(6) without time zone CONSTRAINT "DF__StageAppr__Reque__29E1370A" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "RequestNote" citext,
    "Status" smallint CONSTRAINT "DF__StageAppr__Statu__2BC97F7C" DEFAULT 1 NOT NULL,
    "ReviewedById" uuid,
    "ReviewedAt" timestamp(6) without time zone,
    "AdminNote" citext,
    "ExceptionType" smallint,
    "MinPaymentRequired" numeric(18,2),
    "AmountPaid" numeric(18,2),
    CONSTRAINT "PK_T_SAR" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."StageTypes" (
    "Id" uuid CONSTRAINT "DF__StageTypes__Id__50FB042B" DEFAULT gen_random_uuid() NOT NULL,
    "StageCode" citext NOT NULL,
    "Name" citext NOT NULL,
    "RequiredAction" smallint,
    "DocumentTypeRequired" smallint,
    "ActionLabel" citext,
    "ActionFields" citext,
    "Description" citext,
    "IsActive" boolean CONSTRAINT "DF_T_ST_Active" DEFAULT true NOT NULL,
    "SortOrder" integer CONSTRAINT "DF_T_ST_Sort" DEFAULT 0 NOT NULL,
    "CreatedAt" timestamp(6) without time zone CONSTRAINT "DF_T_ST_Created" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_T_ST" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."Users" (
    "Id" uuid CONSTRAINT "DF_T_Us_Id" DEFAULT gen_random_uuid() NOT NULL,
    "BranchId" uuid NOT NULL,
    "FullName" citext NOT NULL,
    "Email" citext NOT NULL,
    "PasswordHash" citext NOT NULL,
    "Role" smallint NOT NULL,
    "IsActive" boolean CONSTRAINT "DF_T_Us_Active" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_T_Us_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "LastLoginAt" timestamp(0) without time zone,
    "BaseSalary" numeric(18,2) CONSTRAINT "DF__Users__BaseSalar__51EF2864" DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_T_Users" PRIMARY KEY ("Id")
);
CREATE TABLE "_template"."VisaUploads" (
    "Id" uuid CONSTRAINT "DF__VisaUploads__Id__467D75B8" DEFAULT gen_random_uuid() NOT NULL,
    "UploadedById" uuid NOT NULL,
    "UploadedAt" timestamp(6) without time zone CONSTRAINT "DF__VisaUploa__Uploa__477199F1" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "FileName" citext NOT NULL,
    "FileKey" citext NOT NULL,
    "ExtractedPassportNo" citext,
    "ExtractedVisaNo" citext,
    "ExtractedVisaExpiry" date,
    "ExtractedFullName" citext,
    "MatchStatus" smallint CONSTRAINT "DF__VisaUploa__Match__4589517F" DEFAULT 0 NOT NULL,
    "MatchedCandidateId" uuid,
    "Notes" citext,
    CONSTRAINT "PK_T_VisaUploads" PRIMARY KEY ("Id")
);
CREATE TABLE "public"."__EFMigrationsHistory" (
    "MigrationId" citext NOT NULL,
    "ProductVersion" citext NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);
CREATE TABLE "demorecruitment"."AuditLogs" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Aud_Id" DEFAULT gen_random_uuid() NOT NULL,
    "ActorId" uuid,
    "ActorType" smallint NOT NULL,
    "EventType" citext NOT NULL,
    "EntityType" citext,
    "EntityId" uuid,
    "OldValueJson" citext,
    "NewValueJson" citext,
    "IPAddress" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Aud_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_Aud" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Branches" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Br_Id" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "City" citext,
    "Address" citext,
    "IsActive" boolean CONSTRAINT "DF_demorecruitment_Br_Active" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Br_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_Branches" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Campaigns" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Ca_Id" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "Source" smallint NOT NULL,
    "Status" smallint CONSTRAINT "DF_demorecruitment_Ca_St" DEFAULT 1 NOT NULL,
    "BudgetEGP" numeric(18,2),
    "SpendEGP" numeric(18,2),
    "FacebookCampaignId" citext,
    "FacebookAdSetId" citext,
    "FacebookAdId" citext,
    "UtmSource" citext,
    "UtmMedium" citext,
    "UtmCampaign" citext,
    "UtmContent" citext,
    "UtmTerm" citext,
    "StartDate" date,
    "EndDate" date,
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Ca_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_demorecruitment_Ca" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."CandidateActivities" (
    "Id" uuid CONSTRAINT "DF_demo_CA_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "ActivityType" smallint NOT NULL,
    "Description" citext,
    "Details" citext,
    "CreatedById" uuid,
    "CreatedByName" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demo_CA_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demo_CandidateActivities" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Candidates" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Cnd_Id" DEFAULT gen_random_uuid() NOT NULL,
    "BranchId" uuid NOT NULL,
    "AssignedSalesId" uuid NOT NULL,
    "JobPackageId" uuid NOT NULL,
    "RegisteredById" uuid NOT NULL,
    "FullName" citext NOT NULL,
    "Phone" citext NOT NULL,
    "NationalId" citext,
    "Age" integer,
    "City" citext,
    "Notes" citext,
    "Status" smallint CONSTRAINT "DF_demorecruitment_Cnd_Sts" DEFAULT 1 NOT NULL,
    "TotalPaidEGP" numeric(18,2) CONSTRAINT "DF_demorecruitment_Cnd_Paid" DEFAULT 0 NOT NULL,
    "IsCompleted" boolean CONSTRAINT "DF_demorecruitment_Cnd_Cmp" DEFAULT false NOT NULL,
    "CompletedAt" timestamp(0) without time zone,
    "IsProfileComplete" boolean CONSTRAINT "DF_demorecruitment_Cnd_Prof" DEFAULT false NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Cnd_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    "CurrentPackageStageId" uuid,
    "PassportNumber" citext,
    "PassportExpiry" date,
    "VisaNumber" citext,
    "VisaExpiry" date,
    "CompanyId" uuid,
    "FlightDate" timestamp(0) without time zone,
    "MilitaryStatus" citext CONSTRAINT "DF_demorecruitment_Candidates_MilitaryStatus" DEFAULT '' NOT NULL,
    "ProfileImagePath" citext,
    CONSTRAINT "PK_demorecruitment_Cnd" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."CandidateStageHistory" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_CSH_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "FromStage" smallint,
    "ToStage" smallint NOT NULL,
    "ChangedById" uuid NOT NULL,
    "IsOverride" boolean CONSTRAINT "DF_demorecruitment_CSH_Ov" DEFAULT false NOT NULL,
    "OverrideReason" citext,
    "MeetingOutcome" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_CSH_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "FromStageId" uuid,
    "ToStageId" uuid,
    "Notes" citext,
    CONSTRAINT "PK_demorecruitment_CSH" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Commissions" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Com_Id" DEFAULT gen_random_uuid() NOT NULL,
    "SalesUserId" uuid NOT NULL,
    "CandidateId" uuid NOT NULL,
    "CommissionMonth" date NOT NULL,
    "AmountEGP" numeric(18,2) NOT NULL,
    "DealsThisMonth" integer NOT NULL,
    "Status" smallint CONSTRAINT "DF_demorecruitment_Com_St" DEFAULT 1 NOT NULL,
    "ApprovedById" uuid,
    "ApprovedAt" timestamp(0) without time zone,
    "PaidById" uuid,
    "PaidAt" timestamp(0) without time zone,
    "ReversedReason" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Com_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_Com" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."CommissionSettings" (
    "Id" uuid CONSTRAINT "DF__CommissionSe__Id__6A85CC04" DEFAULT gen_random_uuid() NOT NULL,
    "ResetDayOfMonth" smallint CONSTRAINT "DF__Commissio__Reset__6B79F03D" DEFAULT 1 NOT NULL,
    "UpdatedAt" timestamp(6) without time zone,
    "UpdatedById" uuid,
    CONSTRAINT "PK__Commissi__3214EC07BD47AC89" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."CommissionTiers" (
    "Id" uuid CONSTRAINT "DF__CommissionTi__Id__3429BB53" DEFAULT gen_random_uuid() NOT NULL,
    "MinDeals" integer NOT NULL,
    "MaxDeals" integer,
    "AmountPerDeal" numeric(18,2) NOT NULL,
    "IsActive" boolean CONSTRAINT "DF__Commissio__IsAct__324172E1" DEFAULT true NOT NULL,
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__Commissio__Creat__3335971A" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_demorecruitment_CommissionTiers" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Companies" (
    "Id" uuid CONSTRAINT "DF__Companies__Id__2B947552" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "Country" citext NOT NULL,
    "City" citext,
    "ContactPhone" citext,
    "ContactEmail" citext,
    "ContractStartDate" date,
    "Notes" citext,
    "IsActive" boolean CONSTRAINT "DF__Companies__IsAct__2C88998B" DEFAULT true NOT NULL,
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__Companies__Creat__2D7CBDC4" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    "IsDeleted" boolean CONSTRAINT "DF__Companies__IsDel__2AA05119" DEFAULT false NOT NULL,
    "DeletedAt" timestamp(6) without time zone,
    "DeletedById" uuid,
    CONSTRAINT "PK_demorecruitment_Companies" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."CompanyJobs" (
    "Id" uuid CONSTRAINT "DF__CompanyJobs__Id__13BCEBC1" DEFAULT gen_random_uuid() NOT NULL,
    "CompanyId" uuid NOT NULL,
    "JobTitle" citext NOT NULL,
    "RequestedCount" integer CONSTRAINT "DF__CompanyJo__Reque__15A53433" DEFAULT 1 NOT NULL,
    "Notes" citext,
    "IsActive" boolean CONSTRAINT "DF__CompanyJo__IsAct__12C8C788" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__CompanyJo__Creat__14B10FFA" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_CompanyJobs" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."ContractUploads" (
    "Id" uuid CONSTRAINT "DF__ContractUplo__Id__725BF7F6" DEFAULT gen_random_uuid() NOT NULL,
    "UploadedById" uuid NOT NULL,
    "FileName" citext NOT NULL,
    "FileKey" citext NOT NULL,
    "ExtractedPassportNo" citext,
    "ExtractedEmployerName" citext,
    "ExtractedTransactionNo" citext,
    "MatchStatus" smallint CONSTRAINT "DF__ContractU__Match__73501C2F" DEFAULT 0 NOT NULL,
    "MatchedCandidateId" uuid,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__ContractU__Creat__74444068" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_ContractUploads" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."ConversationFollowUps" (
    "Id" uuid CONSTRAINT "DF__Conversation__Id__0B27A5C0" DEFAULT gen_random_uuid() NOT NULL,
    "ConversationId" uuid NOT NULL,
    "AssignedToId" uuid NOT NULL,
    "CreatedById" uuid NOT NULL,
    "DueAt" timestamp(0) without time zone NOT NULL,
    "Status" smallint CONSTRAINT "DF__Conversat__Statu__0A338187" DEFAULT 1 NOT NULL,
    "Notes" citext,
    "CompletedAt" timestamp(0) without time zone,
    "CompletedById" uuid,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__Conversat__Creat__093F5D4E" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_WA_FU" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."ConversationNotes" (
    "Id" uuid CONSTRAINT "DF__Conversation__Id__6225902D" DEFAULT gen_random_uuid() NOT NULL,
    "ConversationId" uuid NOT NULL,
    "AuthorId" uuid NOT NULL,
    "Body" citext NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__Conversat__Creat__6319B466" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_WA_Note" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Documents" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Doc_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "UploadedById" uuid NOT NULL,
    "DocumentType" smallint NOT NULL,
    "FileName" citext NOT NULL,
    "S3Key" citext NOT NULL,
    "FileSizeBytes" integer NOT NULL,
    "MimeType" citext NOT NULL,
    "UploadedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Doc_UpAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_Doc" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."FollowUpReminders" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_FUR_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "ActivityId" uuid,
    "AssignedToId" uuid NOT NULL,
    "CreatedById" uuid NOT NULL,
    "ReminderDate" date NOT NULL,
    "Status" smallint CONSTRAINT "DF_demorecruitment_FUR_St" DEFAULT 1 NOT NULL,
    "SnoozedUntil" date,
    "SnoozeCount" integer CONSTRAINT "DF_demorecruitment_FUR_Snz" DEFAULT 0 NOT NULL,
    "NotificationId" uuid,
    "DismissedAt" timestamp(0) without time zone,
    "DismissedById" uuid,
    "Notes" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_FUR_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    "CandidateId" uuid,
    CONSTRAINT "PK_demorecruitment_FUR" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."JobPackages" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_JP_Id" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "DestinationCountry" citext NOT NULL,
    "JobTitle" citext NOT NULL,
    "PriceEGP" numeric(18,2) NOT NULL,
    "Description" citext,
    "IsActive" boolean CONSTRAINT "DF_demorecruitment_JP_Act" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_JP_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_JP" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."LeadActivities" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_LA_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "ActivityType" smallint NOT NULL,
    "Description" citext,
    "Details" citext,
    "NextFollowUpDate" date,
    "ReminderId" uuid,
    "EntityId" uuid,
    "EntityType" citext,
    "CreatedById" uuid,
    "CreatedByName" citext,
    "ActorType" smallint CONSTRAINT "DF_demorecruitment_LA_Act" DEFAULT 1 NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_LA_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_LA" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."LeadCallLog" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_LCL_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "CalledById" uuid NOT NULL,
    "Channel" smallint NOT NULL,
    "Outcome" smallint NOT NULL,
    "Note" citext,
    "CalledAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_LCL_At" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_LCL" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."LeadFormSettings" (
    "Id" uuid CONSTRAINT "DF__LeadFormSett__Id__762C88DA" DEFAULT gen_random_uuid() NOT NULL,
    "SeniorAgeThreshold" smallint CONSTRAINT "DF__LeadFormS__Senio__753864A1" DEFAULT 45 NOT NULL,
    "SalesWhatsAppNumber" citext,
    "SalesWhatsAppMessage" citext,
    "UpdatedAt" timestamp(0) without time zone,
    "UpdatedById" uuid,
    CONSTRAINT "PK_demorecruitment_LFS" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."LeadFunnelHistory" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_LFH_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "FromStatus" smallint,
    "ToStatus" smallint NOT NULL,
    "ChangedById" uuid NOT NULL,
    "Note" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_LFH_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_LFH" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Leads" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Ld_Id" DEFAULT gen_random_uuid() NOT NULL,
    "BranchId" uuid NOT NULL,
    "AssignedSalesId" uuid,
    "CampaignId" uuid,
    "RegisteredById" uuid NOT NULL,
    "FullName" citext NOT NULL,
    "Phone" citext NOT NULL,
    "LeadSource" smallint NOT NULL,
    "Status" smallint CONSTRAINT "DF_demorecruitment_Ld_St" DEFAULT 1 NOT NULL,
    "Notes" citext,
    "InterestedJobTitle" citext,
    "InterestedCountry" citext,
    "ReferredByName" citext,
    "ReferredByPhone" citext,
    "IsConverted" boolean CONSTRAINT "DF_demorecruitment_Ld_Conv" DEFAULT false NOT NULL,
    "ConvertedAt" timestamp(0) without time zone,
    "ConvertedCandidateId" uuid,
    "FacebookLeadId" citext,
    "FacebookFormId" citext,
    "UtmSource" citext,
    "UtmMedium" citext,
    "UtmCampaign" citext,
    "UtmContent" citext,
    "DuplicateOfLeadId" uuid,
    "IsDuplicate" boolean CONSTRAINT "DF_demorecruitment_Ld_Dup" DEFAULT false NOT NULL,
    "LeadSequence" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "LeadCode" citext GENERATED ALWAYS AS (('LD-' || right('00000' || ("LeadSequence")::text, 5))::citext) STORED,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Ld_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    "LastContactedAt" timestamp(0) without time zone,
    "AssignedOfficeSalesId" uuid,
    "AppointmentDate" timestamp(0) without time zone,
    "GoogleSheetId" uuid,
    "Age" smallint,
    "TeamManagerId" uuid,
    CONSTRAINT "PK_demorecruitment_Ld" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."LeadVisits" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_LV_Id" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "ReceptionUserId" uuid NOT NULL,
    "AssignedSalesUserId" uuid,
    "VisitDateTime" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_LV_VDT" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "MeetingOutcome" smallint NOT NULL,
    "ConvertedCandidateId" uuid,
    "JobPackageId" uuid,
    "Notes" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_LV_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_LV" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."MetaSystemCredentials" (
    "Id" uuid CONSTRAINT "DF__MetaSystemCr__Id__2F650636" DEFAULT gen_random_uuid() NOT NULL,
    "AccessToken" citext NOT NULL,
    "ObtainedAt" timestamp(0) without time zone NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__MetaSyste__Creat__2E70E1FD" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_demorecruitment_Meta_Cred" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Notifications" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Not_Id" DEFAULT gen_random_uuid() NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" smallint NOT NULL,
    "Title" citext NOT NULL,
    "Body" citext,
    "EntityId" uuid,
    "IsRead" boolean CONSTRAINT "DF_demorecruitment_Not_Read" DEFAULT false NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Not_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "Link" citext,
    "ReadAt" timestamp(6) without time zone,
    CONSTRAINT "PK_demorecruitment_Not" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."PackageStages" (
    "Id" uuid CONSTRAINT "DF_demo_PS_Id" DEFAULT gen_random_uuid() NOT NULL,
    "PackageId" uuid NOT NULL,
    "StageName" citext NOT NULL,
    "StageOrder" integer NOT NULL,
    "RequiredMinPaymentEGP" numeric(18,2),
    "Description" citext,
    "NotifySalesOnEnter" boolean CONSTRAINT "DF_demo_PS_Notif" DEFAULT false NOT NULL,
    "IsActive" boolean CONSTRAINT "DF_demo_PS_Active" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demo_PS_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "StageTypeId" uuid,
    "NotifyAdminOnEnter" boolean CONSTRAINT "DF_DR_PS_NotifAdmin" DEFAULT false NOT NULL,
    "RequiresAdminApproval" boolean CONSTRAINT "DF_DR_PS_AdminApproval" DEFAULT false NOT NULL,
    CONSTRAINT "PK_demo_PackageStages" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."PassportDownloadedCandidates" (
    "Id" uuid CONSTRAINT "DF__PassportDown__Id__24E777C3" DEFAULT gen_random_uuid() NOT NULL,
    "LogId" uuid NOT NULL,
    "CandidateId" uuid NOT NULL,
    "DocumentId" uuid,
    "DownloadedAt" timestamp(6) without time zone CONSTRAINT "DF__PassportD__Downl__25DB9BFC" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_PDC" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."PassportDownloadLogs" (
    "Id" uuid CONSTRAINT "DF__PassportDown__Id__4CF5691D" DEFAULT gen_random_uuid() NOT NULL,
    "PackageId" uuid NOT NULL,
    "DownloadedById" uuid NOT NULL,
    "DownloadedAt" timestamp(6) without time zone CONSTRAINT "DF__PassportD__Downl__4DE98D56" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "PassportCount" integer NOT NULL,
    "IsNewOnly" boolean CONSTRAINT "DF__PassportD__IsNew__4C0144E4" DEFAULT false NOT NULL,
    CONSTRAINT "PK_PDL" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Payments" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Pay_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "RecordedById" uuid NOT NULL,
    "AmountEGP" numeric(18,2) NOT NULL,
    "PaymentDate" date NOT NULL,
    "PaymentMethod" smallint NOT NULL,
    "TransactionType" smallint NOT NULL,
    "Notes" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Pay_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "Status" smallint CONSTRAINT "DF__Payments__Status__178D7CA5" DEFAULT 1 NOT NULL,
    "ApprovedById" uuid,
    "ApprovedAt" timestamp(6) without time zone,
    "RejectionReason" citext,
    CONSTRAINT "PK_demorecruitment_Pay" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."RefreshTokens" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_RT_Id" DEFAULT gen_random_uuid() NOT NULL,
    "UserId" uuid NOT NULL,
    "Token" citext NOT NULL,
    "ExpiresAt" timestamp(0) without time zone NOT NULL,
    "IsRevoked" boolean CONSTRAINT "DF_demorecruitment_RT_Rev" DEFAULT false NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_RT_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_demorecruitment_RT" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Refunds" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Ref_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "AmountEGP" numeric(18,2) NOT NULL,
    "Reason" citext NOT NULL,
    "Status" smallint CONSTRAINT "DF_demorecruitment_Ref_St" DEFAULT 1 NOT NULL,
    "RequestedById" uuid NOT NULL,
    "RequestedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Ref_ReqAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "ReviewedById" uuid,
    "ReviewedAt" timestamp(0) without time zone,
    "RejectReason" citext,
    "ExecutedById" uuid,
    "ExecutedAt" timestamp(0) without time zone,
    "RefundPaymentId" uuid,
    CONSTRAINT "PK_demorecruitment_Ref" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."SalaryPayments" (
    "Id" uuid CONSTRAINT "DF__SalaryPaymen__Id__5B438874" DEFAULT gen_random_uuid() NOT NULL,
    "UserId" uuid NOT NULL,
    "SalaryMonth" date NOT NULL,
    "BaseSalary" numeric(18,2) NOT NULL,
    "Adjustment" numeric(18,2) CONSTRAINT "DF__SalaryPay__Adjus__595B4002" DEFAULT 0 NOT NULL,
    "AdjustmentNote" citext,
    "TotalAmount" numeric(19,2) GENERATED ALWAYS AS (("BaseSalary" + "Adjustment")) STORED,
    "Status" smallint CONSTRAINT "DF__SalaryPay__Statu__5C37ACAD" DEFAULT 1 NOT NULL,
    "ApprovedById" uuid,
    "ApprovedAt" timestamp(0) without time zone,
    "PaidById" uuid,
    "PaidAt" timestamp(0) without time zone,
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__SalaryPay__Creat__58671BC9" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    "Notes" citext,
    "PaymentNumber" smallint CONSTRAINT "DF__SalaryPay__Payme__5A4F643B" DEFAULT 1 NOT NULL,
    CONSTRAINT "PK_demorecruitment_SalaryPayments" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."SalesGoogleSheets" (
    "Id" uuid CONSTRAINT "DF__SalesGoogleS__Id__7814D14C" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "SpreadsheetId" citext NOT NULL,
    "SheetName" citext CONSTRAINT "DF__SalesGoog__Sheet__7BE56230" DEFAULT 'Sheet1' NOT NULL,
    "CampaignId" uuid,
    "IsActive" boolean CONSTRAINT "DF__SalesGoog__IsAct__7908F585" DEFAULT true NOT NULL,
    "LastImportedAt" timestamp(6) without time zone,
    "LastImportedRow" integer CONSTRAINT "DF__SalesGoog__LastI__7AF13DF7" DEFAULT 1 NOT NULL,
    "TotalImported" integer CONSTRAINT "DF__SalesGoog__Total__7720AD13" DEFAULT 0 NOT NULL,
    "CreatedById" uuid,
    "CreatedAt" timestamp(6) without time zone CONSTRAINT "DF__SalesGoog__Creat__79FD19BE" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_SalesGoogleSheets" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."SalesGoogleSheetUsers" (
    "Id" uuid CONSTRAINT "DF__SalesGoogleS__Id__02925FBF" DEFAULT gen_random_uuid() NOT NULL,
    "SheetId" uuid NOT NULL,
    "SalesUserId" uuid NOT NULL,
    "IsActive" boolean CONSTRAINT "DF__SalesGoog__IsAct__038683F8" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(6) without time zone CONSTRAINT "DF__SalesGoog__Creat__047AA831" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_SalesGoogleSheetUsers" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."StageActionCompletions" (
    "Id" uuid CONSTRAINT "DF__StageActionC__Id__4FD1D5C8" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "PackageStageId" uuid NOT NULL,
    "CompletedAt" timestamp(6) without time zone CONSTRAINT "DF__StageActi__Compl__4EDDB18F" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "CompletedById" uuid NOT NULL,
    "CompletionType" smallint NOT NULL,
    "Notes" citext,
    CONSTRAINT "PK_SAC" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."StageApprovalRequests" (
    "Id" uuid CONSTRAINT "DF__StageApprova__Id__6501FCD8" DEFAULT gen_random_uuid() NOT NULL,
    "CandidateId" uuid NOT NULL,
    "FromStageId" uuid NOT NULL,
    "ToStageId" uuid NOT NULL,
    "RequestedById" uuid NOT NULL,
    "RequestedAt" timestamp(6) without time zone CONSTRAINT "DF__StageAppr__Reque__65F62111" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "RequestNote" citext,
    "Status" smallint CONSTRAINT "DF__StageAppr__Statu__640DD89F" DEFAULT 1 NOT NULL,
    "ReviewedById" uuid,
    "ReviewedAt" timestamp(6) without time zone,
    "AdminNote" citext,
    "ExceptionType" smallint,
    "MinPaymentRequired" numeric(18,2),
    "AmountPaid" numeric(18,2),
    CONSTRAINT "PK_SAR" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."StageTypes" (
    "Id" uuid CONSTRAINT "DF__StageTypes__Id__6F7F8B4B" DEFAULT gen_random_uuid() NOT NULL,
    "StageCode" citext NOT NULL,
    "Name" citext NOT NULL,
    "RequiredAction" smallint,
    "DocumentTypeRequired" smallint,
    "ActionLabel" citext,
    "ActionFields" citext,
    "Description" citext,
    "IsActive" boolean CONSTRAINT "DF_DR_ST_Active" DEFAULT true NOT NULL,
    "SortOrder" integer CONSTRAINT "DF_DR_ST_Sort" DEFAULT 0 NOT NULL,
    "CreatedAt" timestamp(6) without time zone CONSTRAINT "DF_DR_ST_Created" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    CONSTRAINT "PK_DR_ST" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."TeamLeadForms" (
    "Id" uuid CONSTRAINT "DF__TeamLeadForm__Id__567ED357" DEFAULT gen_random_uuid() NOT NULL,
    "ManagerId" uuid NOT NULL,
    "Slug" citext NOT NULL,
    "WhatsAppNumber" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__TeamLeadF__Creat__5772F790" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_demorecruitment_TLF" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."Users" (
    "Id" uuid CONSTRAINT "DF_demorecruitment_Us_Id" DEFAULT gen_random_uuid() NOT NULL,
    "BranchId" uuid NOT NULL,
    "FullName" citext NOT NULL,
    "Email" citext NOT NULL,
    "PasswordHash" citext NOT NULL,
    "Role" smallint NOT NULL,
    "IsActive" boolean CONSTRAINT "DF_demorecruitment_Us_Act" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_demorecruitment_Us_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "LastLoginAt" timestamp(0) without time zone,
    "BaseSalary" numeric(18,2) CONSTRAINT "DF__Users__BaseSalar__29AC2CE0" DEFAULT 0 NOT NULL,
    "ManagerId" uuid,
    CONSTRAINT "PK_demorecruitment_Users" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."VisaUploads" (
    "Id" uuid CONSTRAINT "DF__VisaUploads__Id__53A266AC" DEFAULT gen_random_uuid() NOT NULL,
    "UploadedById" uuid NOT NULL,
    "UploadedAt" timestamp(6) without time zone CONSTRAINT "DF__VisaUploa__Uploa__54968AE5" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "FileName" citext NOT NULL,
    "FileKey" citext NOT NULL,
    "ExtractedPassportNo" citext,
    "ExtractedVisaNo" citext,
    "ExtractedVisaExpiry" date,
    "ExtractedFullName" citext,
    "MatchStatus" smallint CONSTRAINT "DF__VisaUploa__Match__558AAF1E" DEFAULT 0 NOT NULL,
    "MatchedCandidateId" uuid,
    "Notes" citext,
    CONSTRAINT "PK_VisaUploads" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."WhatsAppAccounts" (
    "Id" uuid CONSTRAINT "DF__WhatsAppAcco__Id__436BFEE3" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext NOT NULL,
    "DisplayPhoneNumber" citext NOT NULL,
    "PhoneNumberId" citext NOT NULL,
    "WabaId" citext NOT NULL,
    "AssignedSalesAgentId" uuid,
    "IsActive" boolean CONSTRAINT "DF__WhatsAppA__IsAct__4460231C" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__WhatsAppA__Creat__46486B8E" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    "ConnectionMode" smallint CONSTRAINT "DF__WhatsAppA__Conne__45544755" DEFAULT 1 NOT NULL,
    "VerifiedName" citext,
    "WebhookSubscriptionStatus" smallint CONSTRAINT "DF__WhatsAppA__Webho__473C8FC7" DEFAULT 1 NOT NULL,
    CONSTRAINT "PK_demorecruitment_WA_Acc" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."WhatsAppContacts" (
    "Id" uuid CONSTRAINT "DF__WhatsAppCont__Id__603D47BB" DEFAULT gen_random_uuid() NOT NULL,
    "Name" citext,
    "WhatsAppPhoneNumber" citext NOT NULL,
    "WhatsAppUserId" citext,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__WhatsAppC__Creat__61316BF4" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    "LastSeenAt" timestamp(0) without time zone,
    CONSTRAINT "PK_demorecruitment_WA_Cnt" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."WhatsAppConversations" (
    "Id" uuid CONSTRAINT "DF__WhatsAppConv__Id__220B0B18" DEFAULT gen_random_uuid() NOT NULL,
    "ContactId" uuid NOT NULL,
    "WhatsAppAccountId" uuid NOT NULL,
    "AssignedSalesAgentId" uuid,
    "LeadId" uuid,
    "Status" smallint CONSTRAINT "DF__WhatsAppC__Statu__23F3538A" DEFAULT 1 NOT NULL,
    "LeadStage" smallint CONSTRAINT "DF__WhatsAppC__LeadS__22FF2F51" DEFAULT 1 NOT NULL,
    "LostReason" citext,
    "UnreadCount" integer CONSTRAINT "DF__WhatsAppC__Unrea__1F2E9E6D" DEFAULT 0 NOT NULL,
    "OpenedAt" timestamp(0) without time zone CONSTRAINT "DF__WhatsAppC__Opene__2022C2A6" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "LastMessageAt" timestamp(0) without time zone,
    "ClosedAt" timestamp(0) without time zone,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__WhatsAppC__Creat__2116E6DF" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_demorecruitment_WA_Cnv" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."WhatsAppHandoffs" (
    "Id" uuid CONSTRAINT "DF__WhatsAppHand__Id__1C5231C2" DEFAULT gen_random_uuid() NOT NULL,
    "LeadId" uuid NOT NULL,
    "WhatsAppAccountId" uuid NOT NULL,
    "AssignedSalesAgentId" uuid NOT NULL,
    "ReferenceCode" citext NOT NULL,
    "GeneratedWhatsAppUrl" citext NOT NULL,
    "Status" smallint CONSTRAINT "DF__WhatsAppH__Statu__1E3A7A34" DEFAULT 1 NOT NULL,
    "ConversationId" uuid,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__WhatsAppH__Creat__1D4655FB" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "SentAt" timestamp(0) without time zone,
    "ConnectedAt" timestamp(0) without time zone,
    "ExpiredAt" timestamp(0) without time zone,
    CONSTRAINT "PK_demorecruitment_WA_Hnd" PRIMARY KEY ("Id")
);
CREATE TABLE "demorecruitment"."WhatsAppMessages" (
    "Id" uuid CONSTRAINT "DF__WhatsAppMess__Id__056ECC6A" DEFAULT gen_random_uuid() NOT NULL,
    "ConversationId" uuid NOT NULL,
    "WhatsAppAccountId" uuid NOT NULL,
    "WhatsAppMessageId" citext,
    "Direction" smallint NOT NULL,
    "MessageType" smallint CONSTRAINT "DF__WhatsAppM__Messa__084B3915" DEFAULT 1 NOT NULL,
    "TextBody" citext,
    "MediaId" citext,
    "MediaUrl" citext,
    "SenderUserId" uuid,
    "ReplyToMessageId" uuid,
    "Status" smallint NOT NULL,
    "ErrorCode" citext,
    "ErrorMessage" citext,
    "WhatsAppTimestamp" timestamp(0) without time zone NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF__WhatsAppM__Creat__075714DC" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "MessageSource" smallint CONSTRAINT "DF__WhatsAppM__Messa__0662F0A3" DEFAULT 1 NOT NULL,
    CONSTRAINT "PK_demorecruitment_WA_Msg" PRIMARY KEY ("Id")
);
CREATE TABLE "platform"."SuperAdminUsers" (
    "Id" uuid CONSTRAINT "DF_SA_Id" DEFAULT gen_random_uuid() NOT NULL,
    "FullName" citext NOT NULL,
    "Email" citext NOT NULL,
    "PasswordHash" citext NOT NULL,
    "IsActive" boolean CONSTRAINT "DF_SA_Active" DEFAULT true NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_SA_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "LastLoginAt" timestamp(0) without time zone,
    CONSTRAINT "PK_SuperAdminUsers" PRIMARY KEY ("Id")
);
CREATE TABLE "platform"."Tenants" (
    "Id" uuid CONSTRAINT "DF_Ten_Id" DEFAULT gen_random_uuid() NOT NULL,
    "CompanyName" citext NOT NULL,
    "SchemaName" citext NOT NULL,
    "Subdomain" citext NOT NULL,
    "SubscriptionStatus" smallint CONSTRAINT "DF_Ten_SubSt" DEFAULT 2 NOT NULL,
    "SubscriptionEndDate" timestamp(0) without time zone NOT NULL,
    "StorageUsedBytes" bigint CONSTRAINT "DF_Ten_Storage" DEFAULT 0 NOT NULL,
    "StorageQuotaBytes" bigint CONSTRAINT "DF_Ten_Quota" DEFAULT 10737418240 NOT NULL,
    "IsActive" boolean CONSTRAINT "DF_Ten_Active" DEFAULT true NOT NULL,
    "CreatedBySuperAdminId" uuid NOT NULL,
    "CreatedAt" timestamp(0) without time zone CONSTRAINT "DF_Ten_CreAt" DEFAULT (clock_timestamp() AT TIME ZONE 'utc') NOT NULL,
    "UpdatedAt" timestamp(0) without time zone,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
);
