-- Generated by PgMigrator. Unique constraints, check constraints, length limits, indexes, foreign keys.
-- [_template].[AuditLogs]
ALTER TABLE "_template"."AuditLogs" ADD CONSTRAINT "CK_T_Aud_ActType" CHECK ("ActorType"=(2) OR "ActorType"=(1));
ALTER TABLE "_template"."AuditLogs" ADD CONSTRAINT "LEN_AuditLogs_EventType" CHECK (char_length("EventType") <= 100);
ALTER TABLE "_template"."AuditLogs" ADD CONSTRAINT "LEN_AuditLogs_EntityType" CHECK (char_length("EntityType") <= 100);
ALTER TABLE "_template"."AuditLogs" ADD CONSTRAINT "LEN_AuditLogs_IPAddress" CHECK (char_length("IPAddress") <= 50);
CREATE INDEX "IX_T_Aud_EntityId" ON "_template"."AuditLogs" ("EntityId", "CreatedAt" DESC);
CREATE INDEX "IX_T_Aud_EventType" ON "_template"."AuditLogs" ("EventType", "CreatedAt" DESC);
CREATE INDEX "IX_T_Aud_CreatedAt" ON "_template"."AuditLogs" ("CreatedAt" DESC);
-- [_template].[Branches]
ALTER TABLE "_template"."Branches" ADD CONSTRAINT "LEN_Branches_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "_template"."Branches" ADD CONSTRAINT "LEN_Branches_City" CHECK (char_length("City") <= 100);
ALTER TABLE "_template"."Branches" ADD CONSTRAINT "LEN_Branches_Address" CHECK (char_length("Address") <= 500);
-- [_template].[Campaigns]
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "CK_T_Camp_Budget" CHECK ("BudgetEGP" IS NULL OR "BudgetEGP">=(0));
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "CK_T_Camp_Dates" CHECK ("EndDate" IS NULL OR "StartDate" IS NULL OR "EndDate">="StartDate");
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "CK_T_Camp_Source" CHECK ("Source">=(1) AND "Source"<=(6));
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "CK_T_Camp_Spend" CHECK ("SpendEGP" IS NULL OR "SpendEGP">=(0));
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "CK_T_Camp_Status" CHECK ("Status">=(1) AND "Status"<=(3));
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_FacebookCampaignId" CHECK (char_length("FacebookCampaignId") <= 100);
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_FacebookAdSetId" CHECK (char_length("FacebookAdSetId") <= 100);
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_FacebookAdId" CHECK (char_length("FacebookAdId") <= 100);
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmSource" CHECK (char_length("UtmSource") <= 100);
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmMedium" CHECK (char_length("UtmMedium") <= 100);
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmCampaign" CHECK (char_length("UtmCampaign") <= 200);
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmContent" CHECK (char_length("UtmContent") <= 200);
ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmTerm" CHECK (char_length("UtmTerm") <= 200);
CREATE INDEX "IX_T_Camp_Status" ON "_template"."Campaigns" ("Status");
CREATE INDEX "IX_T_Camp_Source" ON "_template"."Campaigns" ("Source");
-- [_template].[CandidateActivities]
ALTER TABLE "_template"."CandidateActivities" ADD CONSTRAINT "CK_T_CA_Type" CHECK ("ActivityType">=(1) AND "ActivityType"<=(7));
ALTER TABLE "_template"."CandidateActivities" ADD CONSTRAINT "LEN_CandidateActivities_Description" CHECK (char_length("Description") <= 1000);
ALTER TABLE "_template"."CandidateActivities" ADD CONSTRAINT "LEN_CandidateActivities_CreatedByName" CHECK (char_length("CreatedByName") <= 200);
CREATE INDEX "IX_T_CA_CandId" ON "_template"."CandidateActivities" ("CandidateId", "CreatedAt" DESC);
-- [_template].[Candidates]
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "CK_T_Cand_Status" CHECK ("Status">=(1) AND "Status"<=(3));
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "LEN_Candidates_FullName" CHECK (char_length("FullName") <= 200);
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "LEN_Candidates_Phone" CHECK (char_length("Phone") <= 30);
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "LEN_Candidates_NationalId" CHECK (char_length("NationalId") <= 50);
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "LEN_Candidates_City" CHECK (char_length("City") <= 100);
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "LEN_Candidates_PassportNumber" CHECK (char_length("PassportNumber") <= 50);
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "LEN_Candidates_VisaNumber" CHECK (char_length("VisaNumber") <= 100);
CREATE INDEX "IX_T_Cand_Name" ON "_template"."Candidates" ("FullName") INCLUDE ("Id", "Phone", "Status");
CREATE UNIQUE INDEX "UIX_T_Cand_Passport" ON "_template"."Candidates" ("PassportNumber") WHERE ("PassportNumber" IS NOT NULL);
CREATE INDEX "IX_T_Cand_Sales" ON "_template"."Candidates" ("AssignedSalesId") INCLUDE ("Id", "FullName", "IsCompleted", "IsProfileComplete");
CREATE INDEX "IX_T_Cand_Phone" ON "_template"."Candidates" ("Phone") INCLUDE ("Id", "FullName", "Status");
CREATE INDEX "IX_T_Cand_NatId" ON "_template"."Candidates" ("NationalId") INCLUDE ("Id", "FullName", "Phone");
CREATE INDEX "IX_T_Cand_Profile" ON "_template"."Candidates" ("IsProfileComplete") INCLUDE ("Id", "AssignedSalesId");
-- [_template].[CandidateStageHistory]
ALTER TABLE "_template"."CandidateStageHistory" ADD CONSTRAINT "LEN_CandidateStageHistory_OverrideReason" CHECK (char_length("OverrideReason") <= 500);
ALTER TABLE "_template"."CandidateStageHistory" ADD CONSTRAINT "LEN_CandidateStageHistory_Notes" CHECK (char_length("Notes") <= 500);
CREATE INDEX "IX_T_CSH_CandId" ON "_template"."CandidateStageHistory" ("CandidateId", "CreatedAt" DESC);
-- [_template].[Commissions]
ALTER TABLE "_template"."Commissions" ADD CONSTRAINT "UQ_T_Com_PerDeal" UNIQUE NULLS NOT DISTINCT ("CandidateId");
ALTER TABLE "_template"."Commissions" ADD CONSTRAINT "CK_T_Com_Amt" CHECK ("AmountEGP">=(0));
ALTER TABLE "_template"."Commissions" ADD CONSTRAINT "CK_T_Com_Status" CHECK ("Status">=(1) AND "Status"<=(4));
ALTER TABLE "_template"."Commissions" ADD CONSTRAINT "LEN_Commissions_ReversedReason" CHECK (char_length("ReversedReason") <= 500);
CREATE INDEX "IX_T_Com_Status" ON "_template"."Commissions" ("Status") INCLUDE ("SalesUserId", "AmountEGP", "CommissionMonth");
CREATE INDEX "IX_T_Com_SalesMo" ON "_template"."Commissions" ("SalesUserId", "CommissionMonth");
-- [_template].[CommissionTiers]
ALTER TABLE "_template"."CommissionTiers" ADD CONSTRAINT "CK_T_CT_Amount" CHECK ("AmountPerDeal">(0));
ALTER TABLE "_template"."CommissionTiers" ADD CONSTRAINT "CK_T_CT_MinDeals" CHECK ("MinDeals">=(1));
ALTER TABLE "_template"."CommissionTiers" ADD CONSTRAINT "CK_T_CT_Range" CHECK ("MaxDeals" IS NULL OR "MaxDeals">="MinDeals");
CREATE INDEX "IX_T_CT_Active" ON "_template"."CommissionTiers" ("IsActive", "MinDeals");
-- [_template].[Companies]
ALTER TABLE "_template"."Companies" ADD CONSTRAINT "LEN_Companies_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "_template"."Companies" ADD CONSTRAINT "LEN_Companies_Country" CHECK (char_length("Country") <= 100);
ALTER TABLE "_template"."Companies" ADD CONSTRAINT "LEN_Companies_City" CHECK (char_length("City") <= 100);
ALTER TABLE "_template"."Companies" ADD CONSTRAINT "LEN_Companies_ContactPhone" CHECK (char_length("ContactPhone") <= 50);
ALTER TABLE "_template"."Companies" ADD CONSTRAINT "LEN_Companies_ContactEmail" CHECK (char_length("ContactEmail") <= 255);
-- [_template].[CompanyJobs]
ALTER TABLE "_template"."CompanyJobs" ADD CONSTRAINT "LEN_CompanyJobs_JobTitle" CHECK (char_length("JobTitle") <= 200);
ALTER TABLE "_template"."CompanyJobs" ADD CONSTRAINT "LEN_CompanyJobs_Notes" CHECK (char_length("Notes") <= 500);
CREATE INDEX "IX_T_CompanyJobs_CompanyId" ON "_template"."CompanyJobs" ("CompanyId");
-- [_template].[ContractUploads]
ALTER TABLE "_template"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_FileName" CHECK (char_length("FileName") <= 255);
ALTER TABLE "_template"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_FileKey" CHECK (char_length("FileKey") <= 500);
ALTER TABLE "_template"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_ExtractedPassportNo" CHECK (char_length("ExtractedPassportNo") <= 50);
ALTER TABLE "_template"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_ExtractedEmployerName" CHECK (char_length("ExtractedEmployerName") <= 200);
ALTER TABLE "_template"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_ExtractedTransactionNo" CHECK (char_length("ExtractedTransactionNo") <= 100);
-- [_template].[Documents]
ALTER TABLE "_template"."Documents" ADD CONSTRAINT "CK_T_Doc_Mime" CHECK ("MimeType"='image/png' OR "MimeType"='image/jpg' OR "MimeType"='image/jpeg' OR "MimeType"='application/pdf');
ALTER TABLE "_template"."Documents" ADD CONSTRAINT "CK_T_Doc_Size" CHECK ("FileSizeBytes">=(1) AND "FileSizeBytes"<=(3145728));
ALTER TABLE "_template"."Documents" ADD CONSTRAINT "CK_T_Doc_Type" CHECK ("DocumentType">=(1) AND "DocumentType"<=(5));
ALTER TABLE "_template"."Documents" ADD CONSTRAINT "LEN_Documents_FileName" CHECK (char_length("FileName") <= 255);
ALTER TABLE "_template"."Documents" ADD CONSTRAINT "LEN_Documents_S3Key" CHECK (char_length("S3Key") <= 500);
ALTER TABLE "_template"."Documents" ADD CONSTRAINT "LEN_Documents_MimeType" CHECK (char_length("MimeType") <= 100);
CREATE INDEX "IX_T_Doc_CandId" ON "_template"."Documents" ("CandidateId");
-- [_template].[FollowUpReminders]
ALTER TABLE "_template"."FollowUpReminders" ADD CONSTRAINT "CK_T_FUR_Status" CHECK ("Status">=(1) AND "Status"<=(4));
ALTER TABLE "_template"."FollowUpReminders" ADD CONSTRAINT "LEN_FollowUpReminders_Notes" CHECK (char_length("Notes") <= 500);
CREATE INDEX "IX_T_FUR_Date" ON "_template"."FollowUpReminders" ("ReminderDate", "Status") INCLUDE ("LeadId", "AssignedToId");
CREATE INDEX "IX_T_FUR_Assigned" ON "_template"."FollowUpReminders" ("AssignedToId", "Status", "ReminderDate");
CREATE INDEX "IX_T_FUR_LeadId" ON "_template"."FollowUpReminders" ("LeadId", "Status");
-- [_template].[JobPackages]
ALTER TABLE "_template"."JobPackages" ADD CONSTRAINT "CK_T_JP_Price" CHECK ("PriceEGP">(0));
ALTER TABLE "_template"."JobPackages" ADD CONSTRAINT "LEN_JobPackages_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "_template"."JobPackages" ADD CONSTRAINT "LEN_JobPackages_DestinationCountry" CHECK (char_length("DestinationCountry") <= 100);
ALTER TABLE "_template"."JobPackages" ADD CONSTRAINT "LEN_JobPackages_JobTitle" CHECK (char_length("JobTitle") <= 200);
-- [_template].[LeadActivities]
ALTER TABLE "_template"."LeadActivities" ADD CONSTRAINT "CK_T_LA_ActorType" CHECK ("ActorType"=(2) OR "ActorType"=(1));
ALTER TABLE "_template"."LeadActivities" ADD CONSTRAINT "CK_T_LA_Type" CHECK ("ActivityType">=(1) AND "ActivityType"<=(8));
ALTER TABLE "_template"."LeadActivities" ADD CONSTRAINT "LEN_LeadActivities_Description" CHECK (char_length("Description") <= 1000);
ALTER TABLE "_template"."LeadActivities" ADD CONSTRAINT "LEN_LeadActivities_EntityType" CHECK (char_length("EntityType") <= 50);
ALTER TABLE "_template"."LeadActivities" ADD CONSTRAINT "LEN_LeadActivities_CreatedByName" CHECK (char_length("CreatedByName") <= 200);
CREATE INDEX "IX_T_LA_FollowUp" ON "_template"."LeadActivities" ("NextFollowUpDate") WHERE ("NextFollowUpDate" IS NOT NULL);
CREATE INDEX "IX_T_LA_Type" ON "_template"."LeadActivities" ("ActivityType", "CreatedAt" DESC);
CREATE INDEX "IX_T_LA_LeadId" ON "_template"."LeadActivities" ("LeadId", "CreatedAt" DESC);
-- [_template].[LeadCallLog]
ALTER TABLE "_template"."LeadCallLog" ADD CONSTRAINT "CK_T_LCL_Ch" CHECK ("Channel">=(1) AND "Channel"<=(2));
ALTER TABLE "_template"."LeadCallLog" ADD CONSTRAINT "CK_T_LCL_Out" CHECK ("Outcome">=(1) AND "Outcome"<=(5));
ALTER TABLE "_template"."LeadCallLog" ADD CONSTRAINT "LEN_LeadCallLog_Note" CHECK (char_length("Note") <= 500);
CREATE INDEX "IX_T_LCL_LeadId" ON "_template"."LeadCallLog" ("LeadId", "CalledAt" DESC);
-- [_template].[LeadFunnelHistory]
ALTER TABLE "_template"."LeadFunnelHistory" ADD CONSTRAINT "CK_T_LFH_From" CHECK ("FromStatus" IS NULL OR "FromStatus">=(1) AND "FromStatus"<=(8));
ALTER TABLE "_template"."LeadFunnelHistory" ADD CONSTRAINT "CK_T_LFH_To" CHECK ("ToStatus">=(1) AND "ToStatus"<=(8));
ALTER TABLE "_template"."LeadFunnelHistory" ADD CONSTRAINT "LEN_LeadFunnelHistory_Note" CHECK (char_length("Note") <= 500);
CREATE INDEX "IX_T_LFH_LeadId" ON "_template"."LeadFunnelHistory" ("LeadId", "CreatedAt" DESC);
-- [_template].[Leads]
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "UQ_T_Ld_Phone" UNIQUE NULLS NOT DISTINCT ("Phone");
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "UQ_T_Ld_LeadCode" UNIQUE NULLS NOT DISTINCT ("LeadCode");
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "CK_T_Ld_Source" CHECK ("LeadSource">=(1) AND "LeadSource"<=(6));
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "CK_T_Ld_Status" CHECK ("Status">=(1) AND "Status"<=(8));
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_FullName" CHECK (char_length("FullName") <= 200);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_Phone" CHECK (char_length("Phone") <= 30);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_InterestedJobTitle" CHECK (char_length("InterestedJobTitle") <= 200);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_InterestedCountry" CHECK (char_length("InterestedCountry") <= 100);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_ReferredByName" CHECK (char_length("ReferredByName") <= 200);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_ReferredByPhone" CHECK (char_length("ReferredByPhone") <= 30);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_FacebookLeadId" CHECK (char_length("FacebookLeadId") <= 100);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_FacebookFormId" CHECK (char_length("FacebookFormId") <= 100);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_UtmSource" CHECK (char_length("UtmSource") <= 100);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_UtmMedium" CHECK (char_length("UtmMedium") <= 100);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_UtmCampaign" CHECK (char_length("UtmCampaign") <= 200);
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "LEN_Leads_UtmContent" CHECK (char_length("UtmContent") <= 200);
CREATE INDEX "IX_T_Ld_CreatedAt" ON "_template"."Leads" ("CreatedAt" DESC) INCLUDE ("Id", "FullName", "Status", "LeadSource");
CREATE INDEX "IX_T_Ld_BranchId" ON "_template"."Leads" ("BranchId") INCLUDE ("Id", "FullName", "Status", "AssignedSalesId");
CREATE INDEX "IX_T_Ld_SalesId" ON "_template"."Leads" ("AssignedSalesId") INCLUDE ("Id", "FullName", "Status", "CreatedAt");
CREATE INDEX "IX_T_Ld_FullName" ON "_template"."Leads" ("FullName") INCLUDE ("Id", "Phone", "Status", "LeadSource");
CREATE INDEX "IX_T_Ld_CampaignId" ON "_template"."Leads" ("CampaignId") INCLUDE ("Id", "Status", "IsConverted");
CREATE INDEX "IX_T_Ld_FbLeadId" ON "_template"."Leads" ("FacebookLeadId") WHERE ("FacebookLeadId" IS NOT NULL);
CREATE INDEX "IX_T_Ld_Phone" ON "_template"."Leads" ("Phone");
CREATE INDEX "IX_T_Ld_Status" ON "_template"."Leads" ("Status") INCLUDE ("Id", "FullName", "AssignedSalesId", "CreatedAt");
CREATE INDEX "IX_T_Ld_Source" ON "_template"."Leads" ("LeadSource") INCLUDE ("Id", "CampaignId", "CreatedAt");
-- [_template].[LeadVisits]
ALTER TABLE "_template"."LeadVisits" ADD CONSTRAINT "CK_T_LV_Outcome" CHECK ("MeetingOutcome">=(1) AND "MeetingOutcome"<=(5));
ALTER TABLE "_template"."LeadVisits" ADD CONSTRAINT "LEN_LeadVisits_Notes" CHECK (char_length("Notes") <= 1000);
CREATE INDEX "IX_T_LV_BranchId" ON "_template"."LeadVisits" ("BranchId", "VisitDateTime" DESC);
CREATE INDEX "IX_T_LV_LeadId" ON "_template"."LeadVisits" ("LeadId", "CreatedAt" DESC);
-- [_template].[Notifications]
ALTER TABLE "_template"."Notifications" ADD CONSTRAINT "CK_T_Not_Type" CHECK ("Type">=(1) AND "Type"<=(6));
ALTER TABLE "_template"."Notifications" ADD CONSTRAINT "LEN_Notifications_Title" CHECK (char_length("Title") <= 200);
ALTER TABLE "_template"."Notifications" ADD CONSTRAINT "LEN_Notifications_Body" CHECK (char_length("Body") <= 500);
ALTER TABLE "_template"."Notifications" ADD CONSTRAINT "LEN_Notifications_Link" CHECK (char_length("Link") <= 500);
CREATE INDEX "IX_T_Not_UserId" ON "_template"."Notifications" ("UserId", "IsRead", "CreatedAt" DESC);
-- [_template].[PackageStages]
ALTER TABLE "_template"."PackageStages" ADD CONSTRAINT "UQ_T_PS_Order" UNIQUE NULLS NOT DISTINCT ("PackageId", "StageOrder");
ALTER TABLE "_template"."PackageStages" ADD CONSTRAINT "CK_T_PS_MinPay" CHECK ("RequiredMinPaymentEGP" IS NULL OR "RequiredMinPaymentEGP">=(0));
ALTER TABLE "_template"."PackageStages" ADD CONSTRAINT "CK_T_PS_Order" CHECK ("StageOrder">=(1));
ALTER TABLE "_template"."PackageStages" ADD CONSTRAINT "LEN_PackageStages_StageName" CHECK (char_length("StageName") <= 200);
ALTER TABLE "_template"."PackageStages" ADD CONSTRAINT "LEN_PackageStages_Description" CHECK (char_length("Description") <= 500);
CREATE INDEX "IX_T_PS_PackageId" ON "_template"."PackageStages" ("PackageId", "StageOrder");
-- [_template].[PassportDownloadedCandidates]
ALTER TABLE "_template"."PassportDownloadedCandidates" ADD CONSTRAINT "UQ_T_PDC_Candidate" UNIQUE NULLS NOT DISTINCT ("CandidateId");
-- [_template].[PassportDownloadLogs]
-- [_template].[Payments]
ALTER TABLE "_template"."Payments" ADD CONSTRAINT "CK_T_Pay_Amt" CHECK ("AmountEGP">(0));
ALTER TABLE "_template"."Payments" ADD CONSTRAINT "CK_T_Pay_Meth" CHECK ("PaymentMethod">=(1) AND "PaymentMethod"<=(3));
ALTER TABLE "_template"."Payments" ADD CONSTRAINT "CK_T_Pay_TxType" CHECK ("TransactionType"=(2) OR "TransactionType"=(1));
ALTER TABLE "_template"."Payments" ADD CONSTRAINT "LEN_Payments_Notes" CHECK (char_length("Notes") <= 500);
CREATE INDEX "IX_T_Pay_Date" ON "_template"."Payments" ("PaymentDate") INCLUDE ("CandidateId", "AmountEGP", "TransactionType");
CREATE INDEX "IX_T_Pay_CandId" ON "_template"."Payments" ("CandidateId");
-- [_template].[RefreshTokens]
ALTER TABLE "_template"."RefreshTokens" ADD CONSTRAINT "UQ_T_RT_Token" UNIQUE NULLS NOT DISTINCT ("Token");
ALTER TABLE "_template"."RefreshTokens" ADD CONSTRAINT "LEN_RefreshTokens_Token" CHECK (char_length("Token") <= 500);
CREATE INDEX "IX_T_RT_UserId" ON "_template"."RefreshTokens" ("UserId", "IsRevoked");
-- [_template].[Refunds]
ALTER TABLE "_template"."Refunds" ADD CONSTRAINT "CK_T_Ref_Amt" CHECK ("AmountEGP">(0));
ALTER TABLE "_template"."Refunds" ADD CONSTRAINT "CK_T_Ref_Status" CHECK ("Status">=(1) AND "Status"<=(4));
ALTER TABLE "_template"."Refunds" ADD CONSTRAINT "LEN_Refunds_Reason" CHECK (char_length("Reason") <= 500);
ALTER TABLE "_template"."Refunds" ADD CONSTRAINT "LEN_Refunds_RejectReason" CHECK (char_length("RejectReason") <= 500);
-- [_template].[SalaryPayments]
ALTER TABLE "_template"."SalaryPayments" ADD CONSTRAINT "UQ_T_SP_UserMonth" UNIQUE NULLS NOT DISTINCT ("UserId", "SalaryMonth");
ALTER TABLE "_template"."SalaryPayments" ADD CONSTRAINT "CK_T_SP_Status" CHECK ("Status">=(1) AND "Status"<=(3));
ALTER TABLE "_template"."SalaryPayments" ADD CONSTRAINT "LEN_SalaryPayments_AdjustmentNote" CHECK (char_length("AdjustmentNote") <= 500);
CREATE INDEX "IX_T_SP_Month" ON "_template"."SalaryPayments" ("SalaryMonth" DESC);
CREATE INDEX "IX_T_SP_Status" ON "_template"."SalaryPayments" ("Status");
CREATE INDEX "IX_T_SP_UserId" ON "_template"."SalaryPayments" ("UserId");
-- [_template].[StageActionCompletions]
ALTER TABLE "_template"."StageActionCompletions" ADD CONSTRAINT "UQ_T_SAC_CandStage" UNIQUE NULLS NOT DISTINCT ("CandidateId", "PackageStageId");
ALTER TABLE "_template"."StageActionCompletions" ADD CONSTRAINT "LEN_StageActionCompletions_Notes" CHECK (char_length("Notes") <= 500);
-- [_template].[StageApprovalRequests]
ALTER TABLE "_template"."StageApprovalRequests" ADD CONSTRAINT "LEN_StageApprovalRequests_RequestNote" CHECK (char_length("RequestNote") <= 500);
ALTER TABLE "_template"."StageApprovalRequests" ADD CONSTRAINT "LEN_StageApprovalRequests_AdminNote" CHECK (char_length("AdminNote") <= 500);
-- [_template].[StageTypes]
ALTER TABLE "_template"."StageTypes" ADD CONSTRAINT "UQ_T_ST_Code" UNIQUE NULLS NOT DISTINCT ("StageCode");
ALTER TABLE "_template"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_StageCode" CHECK (char_length("StageCode") <= 50);
ALTER TABLE "_template"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "_template"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_ActionLabel" CHECK (char_length("ActionLabel") <= 200);
ALTER TABLE "_template"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_ActionFields" CHECK (char_length("ActionFields") <= 500);
ALTER TABLE "_template"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_Description" CHECK (char_length("Description") <= 500);
-- [_template].[Users]
ALTER TABLE "_template"."Users" ADD CONSTRAINT "UQ_T_Us_Email" UNIQUE NULLS NOT DISTINCT ("Email");
ALTER TABLE "_template"."Users" ADD CONSTRAINT "CK_T_Us_Role" CHECK ("Role">=(1) AND "Role"<=(5));
ALTER TABLE "_template"."Users" ADD CONSTRAINT "LEN_Users_FullName" CHECK (char_length("FullName") <= 200);
ALTER TABLE "_template"."Users" ADD CONSTRAINT "LEN_Users_Email" CHECK (char_length("Email") <= 255);
ALTER TABLE "_template"."Users" ADD CONSTRAINT "LEN_Users_PasswordHash" CHECK (char_length("PasswordHash") <= 500);
CREATE INDEX "IX_T_Us_BranchId" ON "_template"."Users" ("BranchId");
-- [_template].[VisaUploads]
ALTER TABLE "_template"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_FileName" CHECK (char_length("FileName") <= 500);
ALTER TABLE "_template"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_FileKey" CHECK (char_length("FileKey") <= 500);
ALTER TABLE "_template"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_ExtractedPassportNo" CHECK (char_length("ExtractedPassportNo") <= 100);
ALTER TABLE "_template"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_ExtractedVisaNo" CHECK (char_length("ExtractedVisaNo") <= 100);
ALTER TABLE "_template"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_ExtractedFullName" CHECK (char_length("ExtractedFullName") <= 200);
ALTER TABLE "_template"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_Notes" CHECK (char_length("Notes") <= 500);
-- [dbo].[__EFMigrationsHistory]
ALTER TABLE "public"."__EFMigrationsHistory" ADD CONSTRAINT "LEN___EFMigrationsHistory_MigrationId" CHECK (char_length("MigrationId") <= 150);
ALTER TABLE "public"."__EFMigrationsHistory" ADD CONSTRAINT "LEN___EFMigrationsHistory_ProductVersion" CHECK (char_length("ProductVersion") <= 32);
-- [demorecruitment].[AuditLogs]
ALTER TABLE "demorecruitment"."AuditLogs" ADD CONSTRAINT "CK_demorecruitment_Aud_Act" CHECK ("ActorType"=(2) OR "ActorType"=(1));
ALTER TABLE "demorecruitment"."AuditLogs" ADD CONSTRAINT "LEN_AuditLogs_EventType" CHECK (char_length("EventType") <= 100);
ALTER TABLE "demorecruitment"."AuditLogs" ADD CONSTRAINT "LEN_AuditLogs_EntityType" CHECK (char_length("EntityType") <= 100);
ALTER TABLE "demorecruitment"."AuditLogs" ADD CONSTRAINT "LEN_AuditLogs_IPAddress" CHECK (char_length("IPAddress") <= 50);
CREATE INDEX "IX_demorecruitment_Aud_Ev" ON "demorecruitment"."AuditLogs" ("EventType", "CreatedAt" DESC);
CREATE INDEX "IX_demorecruitment_Aud_En" ON "demorecruitment"."AuditLogs" ("EntityId", "CreatedAt" DESC);
CREATE INDEX "IX_demorecruitment_Aud_Dt" ON "demorecruitment"."AuditLogs" ("CreatedAt" DESC);
-- [demorecruitment].[Branches]
ALTER TABLE "demorecruitment"."Branches" ADD CONSTRAINT "LEN_Branches_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "demorecruitment"."Branches" ADD CONSTRAINT "LEN_Branches_City" CHECK (char_length("City") <= 100);
ALTER TABLE "demorecruitment"."Branches" ADD CONSTRAINT "LEN_Branches_Address" CHECK (char_length("Address") <= 500);
-- [demorecruitment].[Campaigns]
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "CK_demorecruitment_Ca_Src" CHECK ("Source">=(1) AND "Source"<=(6));
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "CK_demorecruitment_Ca_St" CHECK ("Status">=(1) AND "Status"<=(3));
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_FacebookCampaignId" CHECK (char_length("FacebookCampaignId") <= 100);
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_FacebookAdSetId" CHECK (char_length("FacebookAdSetId") <= 100);
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_FacebookAdId" CHECK (char_length("FacebookAdId") <= 100);
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmSource" CHECK (char_length("UtmSource") <= 100);
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmMedium" CHECK (char_length("UtmMedium") <= 100);
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmCampaign" CHECK (char_length("UtmCampaign") <= 200);
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmContent" CHECK (char_length("UtmContent") <= 200);
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "LEN_Campaigns_UtmTerm" CHECK (char_length("UtmTerm") <= 200);
CREATE INDEX "IX_demorecruitment_Ca_St" ON "demorecruitment"."Campaigns" ("Status");
-- [demorecruitment].[CandidateActivities]
ALTER TABLE "demorecruitment"."CandidateActivities" ADD CONSTRAINT "CK_demo_CA_Type" CHECK ("ActivityType">=(1) AND "ActivityType"<=(7));
ALTER TABLE "demorecruitment"."CandidateActivities" ADD CONSTRAINT "LEN_CandidateActivities_Description" CHECK (char_length("Description") <= 1000);
ALTER TABLE "demorecruitment"."CandidateActivities" ADD CONSTRAINT "LEN_CandidateActivities_CreatedByName" CHECK (char_length("CreatedByName") <= 200);
CREATE INDEX "IX_demo_CA_CandId" ON "demorecruitment"."CandidateActivities" ("CandidateId", "CreatedAt" DESC);
-- [demorecruitment].[Candidates]
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "CK_demorecruitment_Cnd_Sts" CHECK ("Status">=(1) AND "Status"<=(3));
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "LEN_Candidates_FullName" CHECK (char_length("FullName") <= 200);
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "LEN_Candidates_Phone" CHECK (char_length("Phone") <= 30);
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "LEN_Candidates_NationalId" CHECK (char_length("NationalId") <= 50);
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "LEN_Candidates_City" CHECK (char_length("City") <= 100);
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "LEN_Candidates_PassportNumber" CHECK (char_length("PassportNumber") <= 50);
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "LEN_Candidates_VisaNumber" CHECK (char_length("VisaNumber") <= 100);
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "LEN_Candidates_MilitaryStatus" CHECK (char_length("MilitaryStatus") <= 50);
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "LEN_Candidates_ProfileImagePath" CHECK (char_length("ProfileImagePath") <= 500);
CREATE UNIQUE INDEX "UIX_demo_Cand_Passport" ON "demorecruitment"."Candidates" ("PassportNumber") WHERE ("PassportNumber" IS NOT NULL);
CREATE INDEX "IX_demorecruitment_Cnd_Sa" ON "demorecruitment"."Candidates" ("AssignedSalesId") INCLUDE ("Id", "FullName", "IsCompleted", "IsProfileComplete");
CREATE INDEX "IX_demorecruitment_Cnd_Ph" ON "demorecruitment"."Candidates" ("Phone") INCLUDE ("Id", "FullName", "Status");
CREATE INDEX "IX_demorecruitment_Cnd_Prf" ON "demorecruitment"."Candidates" ("IsProfileComplete") INCLUDE ("Id", "AssignedSalesId");
-- [demorecruitment].[CandidateStageHistory]
ALTER TABLE "demorecruitment"."CandidateStageHistory" ADD CONSTRAINT "LEN_CandidateStageHistory_OverrideReason" CHECK (char_length("OverrideReason") <= 500);
ALTER TABLE "demorecruitment"."CandidateStageHistory" ADD CONSTRAINT "LEN_CandidateStageHistory_Notes" CHECK (char_length("Notes") <= 500);
CREATE INDEX "IX_demorecruitment_CSH_Cnd" ON "demorecruitment"."CandidateStageHistory" ("CandidateId", "CreatedAt" DESC);
-- [demorecruitment].[Commissions]
ALTER TABLE "demorecruitment"."Commissions" ADD CONSTRAINT "UQ_demorecruitment_Com_Cnd" UNIQUE NULLS NOT DISTINCT ("CandidateId");
ALTER TABLE "demorecruitment"."Commissions" ADD CONSTRAINT "CK_demorecruitment_Com_Amt" CHECK ("AmountEGP">=(0));
ALTER TABLE "demorecruitment"."Commissions" ADD CONSTRAINT "CK_demorecruitment_Com_St" CHECK ("Status">=(1) AND "Status"<=(4));
ALTER TABLE "demorecruitment"."Commissions" ADD CONSTRAINT "LEN_Commissions_ReversedReason" CHECK (char_length("ReversedReason") <= 500);
CREATE INDEX "IX_demorecruitment_Com_Mo" ON "demorecruitment"."Commissions" ("SalesUserId", "CommissionMonth");
CREATE INDEX "IX_demorecruitment_Com_St" ON "demorecruitment"."Commissions" ("Status") INCLUDE ("SalesUserId", "AmountEGP", "CommissionMonth");
-- [demorecruitment].[CommissionSettings]
-- [demorecruitment].[CommissionTiers]
ALTER TABLE "demorecruitment"."CommissionTiers" ADD CONSTRAINT "CK_demorecruitment_CT_Amount" CHECK ("AmountPerDeal">(0));
ALTER TABLE "demorecruitment"."CommissionTiers" ADD CONSTRAINT "CK_demorecruitment_CT_MinDeals" CHECK ("MinDeals">=(1));
ALTER TABLE "demorecruitment"."CommissionTiers" ADD CONSTRAINT "CK_demorecruitment_CT_Range" CHECK ("MaxDeals" IS NULL OR "MaxDeals">="MinDeals");
CREATE INDEX "IX_demorecruitment_CT_Active" ON "demorecruitment"."CommissionTiers" ("IsActive", "MinDeals");
-- [demorecruitment].[Companies]
ALTER TABLE "demorecruitment"."Companies" ADD CONSTRAINT "LEN_Companies_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "demorecruitment"."Companies" ADD CONSTRAINT "LEN_Companies_Country" CHECK (char_length("Country") <= 100);
ALTER TABLE "demorecruitment"."Companies" ADD CONSTRAINT "LEN_Companies_City" CHECK (char_length("City") <= 100);
ALTER TABLE "demorecruitment"."Companies" ADD CONSTRAINT "LEN_Companies_ContactPhone" CHECK (char_length("ContactPhone") <= 50);
ALTER TABLE "demorecruitment"."Companies" ADD CONSTRAINT "LEN_Companies_ContactEmail" CHECK (char_length("ContactEmail") <= 255);
-- [demorecruitment].[CompanyJobs]
ALTER TABLE "demorecruitment"."CompanyJobs" ADD CONSTRAINT "LEN_CompanyJobs_JobTitle" CHECK (char_length("JobTitle") <= 200);
ALTER TABLE "demorecruitment"."CompanyJobs" ADD CONSTRAINT "LEN_CompanyJobs_Notes" CHECK (char_length("Notes") <= 500);
CREATE INDEX "IX_demorecruitment_CompanyJobs_CompanyId" ON "demorecruitment"."CompanyJobs" ("CompanyId");
-- [demorecruitment].[ContractUploads]
ALTER TABLE "demorecruitment"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_FileName" CHECK (char_length("FileName") <= 255);
ALTER TABLE "demorecruitment"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_FileKey" CHECK (char_length("FileKey") <= 500);
ALTER TABLE "demorecruitment"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_ExtractedPassportNo" CHECK (char_length("ExtractedPassportNo") <= 50);
ALTER TABLE "demorecruitment"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_ExtractedEmployerName" CHECK (char_length("ExtractedEmployerName") <= 200);
ALTER TABLE "demorecruitment"."ContractUploads" ADD CONSTRAINT "LEN_ContractUploads_ExtractedTransactionNo" CHECK (char_length("ExtractedTransactionNo") <= 100);
CREATE INDEX "IX_demorecruitment_ContractUploads_Status" ON "demorecruitment"."ContractUploads" ("MatchStatus");
CREATE INDEX "IX_demorecruitment_ContractUploads_Candidate" ON "demorecruitment"."ContractUploads" ("MatchedCandidateId") WHERE ("MatchedCandidateId" IS NOT NULL);
-- [demorecruitment].[ConversationFollowUps]
ALTER TABLE "demorecruitment"."ConversationFollowUps" ADD CONSTRAINT "LEN_ConversationFollowUps_Notes" CHECK (char_length("Notes") <= 500);
CREATE INDEX "IX_demorecruitment_WA_FU_Due" ON "demorecruitment"."ConversationFollowUps" ("DueAt");
CREATE INDEX "IX_ConversationFollowUps_CompletedById" ON "demorecruitment"."ConversationFollowUps" ("CompletedById");
CREATE INDEX "IX_demorecruitment_WA_FU_Assignee" ON "demorecruitment"."ConversationFollowUps" ("AssignedToId", "Status", "DueAt");
CREATE INDEX "IX_ConversationFollowUps_CreatedById" ON "demorecruitment"."ConversationFollowUps" ("CreatedById");
CREATE INDEX "IX_demorecruitment_WA_FU_Cnv" ON "demorecruitment"."ConversationFollowUps" ("ConversationId");
-- [demorecruitment].[ConversationNotes]
ALTER TABLE "demorecruitment"."ConversationNotes" ADD CONSTRAINT "LEN_ConversationNotes_Body" CHECK (char_length("Body") <= 1000);
CREATE INDEX "IX_ConversationNotes_AuthorId" ON "demorecruitment"."ConversationNotes" ("AuthorId");
CREATE INDEX "IX_demorecruitment_WA_Note_Cnv" ON "demorecruitment"."ConversationNotes" ("ConversationId", "CreatedAt" DESC);
-- [demorecruitment].[Documents]
ALTER TABLE "demorecruitment"."Documents" ADD CONSTRAINT "CK_demorecruit_Doc_Tp" CHECK ("DocumentType">=(1) AND "DocumentType"<=(5));
ALTER TABLE "demorecruitment"."Documents" ADD CONSTRAINT "CK_demorecruitment_Doc_Mm" CHECK ("MimeType"='image/png' OR "MimeType"='image/jpg' OR "MimeType"='image/jpeg' OR "MimeType"='application/pdf');
ALTER TABLE "demorecruitment"."Documents" ADD CONSTRAINT "CK_demorecruitment_Doc_Sz" CHECK ("FileSizeBytes">=(1) AND "FileSizeBytes"<=(3145728));
ALTER TABLE "demorecruitment"."Documents" ADD CONSTRAINT "LEN_Documents_FileName" CHECK (char_length("FileName") <= 255);
ALTER TABLE "demorecruitment"."Documents" ADD CONSTRAINT "LEN_Documents_S3Key" CHECK (char_length("S3Key") <= 500);
ALTER TABLE "demorecruitment"."Documents" ADD CONSTRAINT "LEN_Documents_MimeType" CHECK (char_length("MimeType") <= 100);
CREATE INDEX "IX_demorecruitment_Doc_Cnd" ON "demorecruitment"."Documents" ("CandidateId");
-- [demorecruitment].[FollowUpReminders]
ALTER TABLE "demorecruitment"."FollowUpReminders" ADD CONSTRAINT "CK_demorecruitment_FUR_St" CHECK ("Status">=(1) AND "Status"<=(4));
ALTER TABLE "demorecruitment"."FollowUpReminders" ADD CONSTRAINT "LEN_FollowUpReminders_Notes" CHECK (char_length("Notes") <= 500);
CREATE INDEX "IX_demorecruitment_FUR_Dt" ON "demorecruitment"."FollowUpReminders" ("ReminderDate", "Status") INCLUDE ("LeadId", "AssignedToId");
CREATE INDEX "IX_demorecruitment_FUR_At" ON "demorecruitment"."FollowUpReminders" ("AssignedToId", "Status", "ReminderDate");
-- [demorecruitment].[JobPackages]
ALTER TABLE "demorecruitment"."JobPackages" ADD CONSTRAINT "CK_demorecruitment_JP_Price" CHECK ("PriceEGP">(0));
ALTER TABLE "demorecruitment"."JobPackages" ADD CONSTRAINT "LEN_JobPackages_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "demorecruitment"."JobPackages" ADD CONSTRAINT "LEN_JobPackages_DestinationCountry" CHECK (char_length("DestinationCountry") <= 100);
ALTER TABLE "demorecruitment"."JobPackages" ADD CONSTRAINT "LEN_JobPackages_JobTitle" CHECK (char_length("JobTitle") <= 200);
-- [demorecruitment].[LeadActivities]
ALTER TABLE "demorecruitment"."LeadActivities" ADD CONSTRAINT "CK_demorecruitment_LA_Act" CHECK ("ActorType"=(2) OR "ActorType"=(1));
ALTER TABLE "demorecruitment"."LeadActivities" ADD CONSTRAINT "CK_demorecruitment_LA_Type" CHECK ("ActivityType">=(1) AND "ActivityType"<=(8));
ALTER TABLE "demorecruitment"."LeadActivities" ADD CONSTRAINT "LEN_LeadActivities_Description" CHECK (char_length("Description") <= 1000);
ALTER TABLE "demorecruitment"."LeadActivities" ADD CONSTRAINT "LEN_LeadActivities_EntityType" CHECK (char_length("EntityType") <= 50);
ALTER TABLE "demorecruitment"."LeadActivities" ADD CONSTRAINT "LEN_LeadActivities_CreatedByName" CHECK (char_length("CreatedByName") <= 200);
CREATE INDEX "IX_demorecruitment_LA_Ld" ON "demorecruitment"."LeadActivities" ("LeadId", "CreatedAt" DESC);
CREATE INDEX "IX_demorecruitment_LA_Fup" ON "demorecruitment"."LeadActivities" ("NextFollowUpDate") WHERE ("NextFollowUpDate" IS NOT NULL);
-- [demorecruitment].[LeadCallLog]
ALTER TABLE "demorecruitment"."LeadCallLog" ADD CONSTRAINT "CK_demorecruitment_LCL_Ch" CHECK ("Channel">=(1) AND "Channel"<=(2));
ALTER TABLE "demorecruitment"."LeadCallLog" ADD CONSTRAINT "CK_demorecruitment_LCL_Out" CHECK ("Outcome">=(1) AND "Outcome"<=(5));
ALTER TABLE "demorecruitment"."LeadCallLog" ADD CONSTRAINT "LEN_LeadCallLog_Note" CHECK (char_length("Note") <= 500);
CREATE INDEX "IX_demorecruitment_LCL_Ld" ON "demorecruitment"."LeadCallLog" ("LeadId", "CalledAt" DESC);
-- [demorecruitment].[LeadFormSettings]
ALTER TABLE "demorecruitment"."LeadFormSettings" ADD CONSTRAINT "LEN_LeadFormSettings_SalesWhatsAppNumber" CHECK (char_length("SalesWhatsAppNumber") <= 30);
ALTER TABLE "demorecruitment"."LeadFormSettings" ADD CONSTRAINT "LEN_LeadFormSettings_SalesWhatsAppMessage" CHECK (char_length("SalesWhatsAppMessage") <= 1000);
-- [demorecruitment].[LeadFunnelHistory]
ALTER TABLE "demorecruitment"."LeadFunnelHistory" ADD CONSTRAINT "CK_demorecruitment_LFH_To" CHECK ("ToStatus">=(1) AND "ToStatus"<=(8));
ALTER TABLE "demorecruitment"."LeadFunnelHistory" ADD CONSTRAINT "LEN_LeadFunnelHistory_Note" CHECK (char_length("Note") <= 500);
CREATE INDEX "IX_demorecruitment_LFH_Ld" ON "demorecruitment"."LeadFunnelHistory" ("LeadId", "CreatedAt" DESC);
-- [demorecruitment].[Leads]
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "UQ_demorecruitment_Ld_Ph" UNIQUE NULLS NOT DISTINCT ("Phone");
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "UQ_demorecruitment_Ld_Code" UNIQUE NULLS NOT DISTINCT ("LeadCode");
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "CK_demorecruitment_Ld_Src" CHECK ("LeadSource">=(1) AND "LeadSource"<=(6));
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "CK_demorecruitment_Ld_St" CHECK ("Status">=(1) AND "Status"<=(8));
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_FullName" CHECK (char_length("FullName") <= 200);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_Phone" CHECK (char_length("Phone") <= 30);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_InterestedJobTitle" CHECK (char_length("InterestedJobTitle") <= 200);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_InterestedCountry" CHECK (char_length("InterestedCountry") <= 100);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_ReferredByName" CHECK (char_length("ReferredByName") <= 200);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_ReferredByPhone" CHECK (char_length("ReferredByPhone") <= 30);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_FacebookLeadId" CHECK (char_length("FacebookLeadId") <= 100);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_FacebookFormId" CHECK (char_length("FacebookFormId") <= 100);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_UtmSource" CHECK (char_length("UtmSource") <= 100);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_UtmMedium" CHECK (char_length("UtmMedium") <= 100);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_UtmCampaign" CHECK (char_length("UtmCampaign") <= 200);
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "LEN_Leads_UtmContent" CHECK (char_length("UtmContent") <= 200);
CREATE INDEX "IX_Leads_GoogleSheetId" ON "demorecruitment"."Leads" ("GoogleSheetId") WHERE ("GoogleSheetId" IS NOT NULL);
CREATE INDEX "IX_demorecruitment_Ld_Src" ON "demorecruitment"."Leads" ("LeadSource") INCLUDE ("Id", "CampaignId", "CreatedAt");
CREATE UNIQUE INDEX "UX_Leads_FacebookLeadId" ON "demorecruitment"."Leads" ("FacebookLeadId") WHERE ("FacebookLeadId" IS NOT NULL);
CREATE INDEX "IX_demorecruitment_Ld_St" ON "demorecruitment"."Leads" ("Status") INCLUDE ("Id", "FullName", "AssignedSalesId", "CreatedAt");
CREATE INDEX "IX_demorecruitment_Ld_TeamMgr" ON "demorecruitment"."Leads" ("TeamManagerId") WHERE ("TeamManagerId" IS NOT NULL);
CREATE INDEX "IX_demorecruitment_Ld_Sa" ON "demorecruitment"."Leads" ("AssignedSalesId") INCLUDE ("Id", "FullName", "Status", "CreatedAt");
CREATE INDEX "IX_demorecruitment_Ld_Ph" ON "demorecruitment"."Leads" ("Phone");
CREATE INDEX "IX_demorecruitment_Ld_Ca" ON "demorecruitment"."Leads" ("CampaignId") INCLUDE ("Id", "Status", "IsConverted");
CREATE INDEX "IX_demorecruitment_Ld_OfSa" ON "demorecruitment"."Leads" ("AssignedOfficeSalesId");
-- [demorecruitment].[LeadVisits]
ALTER TABLE "demorecruitment"."LeadVisits" ADD CONSTRAINT "CK_demorecruitment_LV_Out" CHECK ("MeetingOutcome">=(1) AND "MeetingOutcome"<=(5));
ALTER TABLE "demorecruitment"."LeadVisits" ADD CONSTRAINT "LEN_LeadVisits_Notes" CHECK (char_length("Notes") <= 1000);
CREATE INDEX "IX_demorecruitment_LV_Ld" ON "demorecruitment"."LeadVisits" ("LeadId", "CreatedAt" DESC);
CREATE INDEX "IX_demorecruitment_LV_Br" ON "demorecruitment"."LeadVisits" ("BranchId", "VisitDateTime" DESC);
-- [demorecruitment].[MetaSystemCredentials]
ALTER TABLE "demorecruitment"."MetaSystemCredentials" ADD CONSTRAINT "LEN_MetaSystemCredentials_AccessToken" CHECK (char_length("AccessToken") <= 2000);
-- [demorecruitment].[Notifications]
ALTER TABLE "demorecruitment"."Notifications" ADD CONSTRAINT "CK_demorecruitment_Not_Tp" CHECK ("Type">=(1) AND "Type"<=(6));
ALTER TABLE "demorecruitment"."Notifications" ADD CONSTRAINT "LEN_Notifications_Title" CHECK (char_length("Title") <= 200);
ALTER TABLE "demorecruitment"."Notifications" ADD CONSTRAINT "LEN_Notifications_Body" CHECK (char_length("Body") <= 500);
ALTER TABLE "demorecruitment"."Notifications" ADD CONSTRAINT "LEN_Notifications_Link" CHECK (char_length("Link") <= 500);
CREATE INDEX "IX_demorecruitment_Not_Us" ON "demorecruitment"."Notifications" ("UserId", "IsRead", "CreatedAt" DESC);
-- [demorecruitment].[PackageStages]
ALTER TABLE "demorecruitment"."PackageStages" ADD CONSTRAINT "UQ_demo_PS_Order" UNIQUE NULLS NOT DISTINCT ("PackageId", "StageOrder");
ALTER TABLE "demorecruitment"."PackageStages" ADD CONSTRAINT "CK_demo_PS_MinPay" CHECK ("RequiredMinPaymentEGP" IS NULL OR "RequiredMinPaymentEGP">=(0));
ALTER TABLE "demorecruitment"."PackageStages" ADD CONSTRAINT "CK_demo_PS_Order" CHECK ("StageOrder">=(1));
ALTER TABLE "demorecruitment"."PackageStages" ADD CONSTRAINT "LEN_PackageStages_StageName" CHECK (char_length("StageName") <= 200);
ALTER TABLE "demorecruitment"."PackageStages" ADD CONSTRAINT "LEN_PackageStages_Description" CHECK (char_length("Description") <= 500);
CREATE INDEX "IX_demo_PS_PackageId" ON "demorecruitment"."PackageStages" ("PackageId", "StageOrder");
-- [demorecruitment].[PassportDownloadedCandidates]
ALTER TABLE "demorecruitment"."PassportDownloadedCandidates" ADD CONSTRAINT "UQ_PDC_Candidate" UNIQUE NULLS NOT DISTINCT ("CandidateId");
-- [demorecruitment].[PassportDownloadLogs]
-- [demorecruitment].[Payments]
ALTER TABLE "demorecruitment"."Payments" ADD CONSTRAINT "CK_demorecruitment_Pay_Amt" CHECK ("AmountEGP">(0));
ALTER TABLE "demorecruitment"."Payments" ADD CONSTRAINT "CK_demorecruitment_Pay_Mth" CHECK ("PaymentMethod">=(1) AND "PaymentMethod"<=(3));
ALTER TABLE "demorecruitment"."Payments" ADD CONSTRAINT "CK_demorecruitment_Pay_Tx" CHECK ("TransactionType"=(2) OR "TransactionType"=(1));
ALTER TABLE "demorecruitment"."Payments" ADD CONSTRAINT "LEN_Payments_Notes" CHECK (char_length("Notes") <= 500);
ALTER TABLE "demorecruitment"."Payments" ADD CONSTRAINT "LEN_Payments_RejectionReason" CHECK (char_length("RejectionReason") <= 500);
CREATE INDEX "IX_demorecruitment_Pay_Dt" ON "demorecruitment"."Payments" ("PaymentDate") INCLUDE ("CandidateId", "AmountEGP", "TransactionType");
CREATE INDEX "IX_demorecruitment_Pay_Cnd" ON "demorecruitment"."Payments" ("CandidateId");
-- [demorecruitment].[RefreshTokens]
ALTER TABLE "demorecruitment"."RefreshTokens" ADD CONSTRAINT "UQ_demorecruitment_RT_Tok" UNIQUE NULLS NOT DISTINCT ("Token");
ALTER TABLE "demorecruitment"."RefreshTokens" ADD CONSTRAINT "LEN_RefreshTokens_Token" CHECK (char_length("Token") <= 500);
-- [demorecruitment].[Refunds]
ALTER TABLE "demorecruitment"."Refunds" ADD CONSTRAINT "CK_demorecruitment_Ref_Amt" CHECK ("AmountEGP">(0));
ALTER TABLE "demorecruitment"."Refunds" ADD CONSTRAINT "CK_demorecruitment_Ref_St" CHECK ("Status">=(1) AND "Status"<=(4));
ALTER TABLE "demorecruitment"."Refunds" ADD CONSTRAINT "LEN_Refunds_Reason" CHECK (char_length("Reason") <= 500);
ALTER TABLE "demorecruitment"."Refunds" ADD CONSTRAINT "LEN_Refunds_RejectReason" CHECK (char_length("RejectReason") <= 500);
-- [demorecruitment].[SalaryPayments]
ALTER TABLE "demorecruitment"."SalaryPayments" ADD CONSTRAINT "CK_demorecruitment_SP_Status" CHECK ("Status">=(1) AND "Status"<=(3));
ALTER TABLE "demorecruitment"."SalaryPayments" ADD CONSTRAINT "LEN_SalaryPayments_AdjustmentNote" CHECK (char_length("AdjustmentNote") <= 500);
ALTER TABLE "demorecruitment"."SalaryPayments" ADD CONSTRAINT "LEN_SalaryPayments_Notes" CHECK (char_length("Notes") <= 500);
CREATE INDEX "IX_demorecruitment_SP_UserId" ON "demorecruitment"."SalaryPayments" ("UserId");
CREATE INDEX "IX_demorecruitment_SP_Month" ON "demorecruitment"."SalaryPayments" ("SalaryMonth" DESC);
CREATE INDEX "IX_demorecruitment_SP_Status" ON "demorecruitment"."SalaryPayments" ("Status");
-- [demorecruitment].[SalesGoogleSheets]
ALTER TABLE "demorecruitment"."SalesGoogleSheets" ADD CONSTRAINT "LEN_SalesGoogleSheets_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "demorecruitment"."SalesGoogleSheets" ADD CONSTRAINT "LEN_SalesGoogleSheets_SpreadsheetId" CHECK (char_length("SpreadsheetId") <= 200);
ALTER TABLE "demorecruitment"."SalesGoogleSheets" ADD CONSTRAINT "LEN_SalesGoogleSheets_SheetName" CHECK (char_length("SheetName") <= 200);
-- [demorecruitment].[SalesGoogleSheetUsers]
ALTER TABLE "demorecruitment"."SalesGoogleSheetUsers" ADD CONSTRAINT "UQ_SheetUsers_SheetUser" UNIQUE NULLS NOT DISTINCT ("SheetId", "SalesUserId");
-- [demorecruitment].[StageActionCompletions]
ALTER TABLE "demorecruitment"."StageActionCompletions" ADD CONSTRAINT "UQ_SAC_CandStage" UNIQUE NULLS NOT DISTINCT ("CandidateId", "PackageStageId");
ALTER TABLE "demorecruitment"."StageActionCompletions" ADD CONSTRAINT "LEN_StageActionCompletions_Notes" CHECK (char_length("Notes") <= 500);
-- [demorecruitment].[StageApprovalRequests]
ALTER TABLE "demorecruitment"."StageApprovalRequests" ADD CONSTRAINT "LEN_StageApprovalRequests_RequestNote" CHECK (char_length("RequestNote") <= 500);
ALTER TABLE "demorecruitment"."StageApprovalRequests" ADD CONSTRAINT "LEN_StageApprovalRequests_AdminNote" CHECK (char_length("AdminNote") <= 500);
-- [demorecruitment].[StageTypes]
ALTER TABLE "demorecruitment"."StageTypes" ADD CONSTRAINT "UQ_DR_ST_Code" UNIQUE NULLS NOT DISTINCT ("StageCode");
ALTER TABLE "demorecruitment"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_StageCode" CHECK (char_length("StageCode") <= 50);
ALTER TABLE "demorecruitment"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "demorecruitment"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_ActionLabel" CHECK (char_length("ActionLabel") <= 200);
ALTER TABLE "demorecruitment"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_ActionFields" CHECK (char_length("ActionFields") <= 500);
ALTER TABLE "demorecruitment"."StageTypes" ADD CONSTRAINT "LEN_StageTypes_Description" CHECK (char_length("Description") <= 500);
-- [demorecruitment].[TeamLeadForms]
ALTER TABLE "demorecruitment"."TeamLeadForms" ADD CONSTRAINT "LEN_TeamLeadForms_Slug" CHECK (char_length("Slug") <= 50);
ALTER TABLE "demorecruitment"."TeamLeadForms" ADD CONSTRAINT "LEN_TeamLeadForms_WhatsAppNumber" CHECK (char_length("WhatsAppNumber") <= 30);
CREATE UNIQUE INDEX "UQ_demorecruitment_TLF_Slug" ON "demorecruitment"."TeamLeadForms" ("Slug") NULLS NOT DISTINCT;
CREATE UNIQUE INDEX "UQ_demorecruitment_TLF_Mgr" ON "demorecruitment"."TeamLeadForms" ("ManagerId") NULLS NOT DISTINCT;
-- [demorecruitment].[Users]
ALTER TABLE "demorecruitment"."Users" ADD CONSTRAINT "UQ_demorecruitment_Us_Email" UNIQUE NULLS NOT DISTINCT ("Email");
ALTER TABLE "demorecruitment"."Users" ADD CONSTRAINT "CK_platform_Us_Role" CHECK ("Role"=(7) OR "Role"=(6) OR "Role"=(5) OR "Role"=(4) OR "Role"=(3) OR "Role"=(2) OR "Role"=(1));
ALTER TABLE "demorecruitment"."Users" ADD CONSTRAINT "LEN_Users_FullName" CHECK (char_length("FullName") <= 200);
ALTER TABLE "demorecruitment"."Users" ADD CONSTRAINT "LEN_Users_Email" CHECK (char_length("Email") <= 255);
ALTER TABLE "demorecruitment"."Users" ADD CONSTRAINT "LEN_Users_PasswordHash" CHECK (char_length("PasswordHash") <= 500);
CREATE INDEX "IX_demorecruitment_Us_Br" ON "demorecruitment"."Users" ("BranchId");
-- [demorecruitment].[VisaUploads]
ALTER TABLE "demorecruitment"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_FileName" CHECK (char_length("FileName") <= 500);
ALTER TABLE "demorecruitment"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_FileKey" CHECK (char_length("FileKey") <= 500);
ALTER TABLE "demorecruitment"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_ExtractedPassportNo" CHECK (char_length("ExtractedPassportNo") <= 100);
ALTER TABLE "demorecruitment"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_ExtractedVisaNo" CHECK (char_length("ExtractedVisaNo") <= 100);
ALTER TABLE "demorecruitment"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_ExtractedFullName" CHECK (char_length("ExtractedFullName") <= 200);
ALTER TABLE "demorecruitment"."VisaUploads" ADD CONSTRAINT "LEN_VisaUploads_Notes" CHECK (char_length("Notes") <= 500);
-- [demorecruitment].[WhatsAppAccounts]
ALTER TABLE "demorecruitment"."WhatsAppAccounts" ADD CONSTRAINT "LEN_WhatsAppAccounts_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "demorecruitment"."WhatsAppAccounts" ADD CONSTRAINT "LEN_WhatsAppAccounts_DisplayPhoneNumber" CHECK (char_length("DisplayPhoneNumber") <= 30);
ALTER TABLE "demorecruitment"."WhatsAppAccounts" ADD CONSTRAINT "LEN_WhatsAppAccounts_PhoneNumberId" CHECK (char_length("PhoneNumberId") <= 50);
ALTER TABLE "demorecruitment"."WhatsAppAccounts" ADD CONSTRAINT "LEN_WhatsAppAccounts_WabaId" CHECK (char_length("WabaId") <= 50);
ALTER TABLE "demorecruitment"."WhatsAppAccounts" ADD CONSTRAINT "LEN_WhatsAppAccounts_VerifiedName" CHECK (char_length("VerifiedName") <= 200);
CREATE INDEX "IX_WhatsAppAccounts_AssignedSalesAgentId" ON "demorecruitment"."WhatsAppAccounts" ("AssignedSalesAgentId");
CREATE UNIQUE INDEX "UQ_demorecruitment_WA_Acc_PhoneNumberId" ON "demorecruitment"."WhatsAppAccounts" ("PhoneNumberId") NULLS NOT DISTINCT;
CREATE INDEX "IX_demorecruitment_WA_Acc_Active" ON "demorecruitment"."WhatsAppAccounts" ("IsActive");
-- [demorecruitment].[WhatsAppContacts]
ALTER TABLE "demorecruitment"."WhatsAppContacts" ADD CONSTRAINT "LEN_WhatsAppContacts_Name" CHECK (char_length("Name") <= 200);
ALTER TABLE "demorecruitment"."WhatsAppContacts" ADD CONSTRAINT "LEN_WhatsAppContacts_WhatsAppPhoneNumber" CHECK (char_length("WhatsAppPhoneNumber") <= 30);
ALTER TABLE "demorecruitment"."WhatsAppContacts" ADD CONSTRAINT "LEN_WhatsAppContacts_WhatsAppUserId" CHECK (char_length("WhatsAppUserId") <= 50);
CREATE UNIQUE INDEX "UQ_demorecruitment_WA_Cnt_Phone" ON "demorecruitment"."WhatsAppContacts" ("WhatsAppPhoneNumber") NULLS NOT DISTINCT;
-- [demorecruitment].[WhatsAppConversations]
ALTER TABLE "demorecruitment"."WhatsAppConversations" ADD CONSTRAINT "LEN_WhatsAppConversations_LostReason" CHECK (char_length("LostReason") <= 200);
CREATE UNIQUE INDEX "UQ_demorecruitment_WA_Cnv_Cnt_Acc" ON "demorecruitment"."WhatsAppConversations" ("ContactId", "WhatsAppAccountId") NULLS NOT DISTINCT;
CREATE INDEX "IX_demorecruitment_WA_Cnv_Status" ON "demorecruitment"."WhatsAppConversations" ("Status");
CREATE INDEX "IX_demorecruitment_WA_Cnv_Lead" ON "demorecruitment"."WhatsAppConversations" ("LeadId");
CREATE INDEX "IX_demorecruitment_WA_Cnv_LastMsg" ON "demorecruitment"."WhatsAppConversations" ("LastMessageAt" DESC);
CREATE INDEX "IX_demorecruitment_WA_Cnv_LeadStage" ON "demorecruitment"."WhatsAppConversations" ("LeadStage");
CREATE INDEX "IX_demorecruitment_WA_Cnv_Acc" ON "demorecruitment"."WhatsAppConversations" ("WhatsAppAccountId");
CREATE INDEX "IX_demorecruitment_WA_Cnv_Agent" ON "demorecruitment"."WhatsAppConversations" ("AssignedSalesAgentId");
-- [demorecruitment].[WhatsAppHandoffs]
ALTER TABLE "demorecruitment"."WhatsAppHandoffs" ADD CONSTRAINT "LEN_WhatsAppHandoffs_ReferenceCode" CHECK (char_length("ReferenceCode") <= 20);
ALTER TABLE "demorecruitment"."WhatsAppHandoffs" ADD CONSTRAINT "LEN_WhatsAppHandoffs_GeneratedWhatsAppUrl" CHECK (char_length("GeneratedWhatsAppUrl") <= 500);
CREATE INDEX "IX_WhatsAppHandoffs_AssignedSalesAgentId" ON "demorecruitment"."WhatsAppHandoffs" ("AssignedSalesAgentId");
CREATE INDEX "IX_demorecruitment_WA_Hnd_Status" ON "demorecruitment"."WhatsAppHandoffs" ("Status");
CREATE UNIQUE INDEX "UQ_demorecruitment_WA_Hnd_Ref" ON "demorecruitment"."WhatsAppHandoffs" ("ReferenceCode") NULLS NOT DISTINCT;
CREATE INDEX "IX_demorecruitment_WA_Hnd_Lead" ON "demorecruitment"."WhatsAppHandoffs" ("LeadId");
CREATE INDEX "IX_WhatsAppHandoffs_WhatsAppAccountId" ON "demorecruitment"."WhatsAppHandoffs" ("WhatsAppAccountId");
CREATE INDEX "IX_WhatsAppHandoffs_ConversationId" ON "demorecruitment"."WhatsAppHandoffs" ("ConversationId");
-- [demorecruitment].[WhatsAppMessages]
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "LEN_WhatsAppMessages_WhatsAppMessageId" CHECK (char_length("WhatsAppMessageId") <= 100);
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "LEN_WhatsAppMessages_TextBody" CHECK (char_length("TextBody") <= 4000);
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "LEN_WhatsAppMessages_MediaId" CHECK (char_length("MediaId") <= 200);
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "LEN_WhatsAppMessages_MediaUrl" CHECK (char_length("MediaUrl") <= 1000);
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "LEN_WhatsAppMessages_ErrorCode" CHECK (char_length("ErrorCode") <= 50);
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "LEN_WhatsAppMessages_ErrorMessage" CHECK (char_length("ErrorMessage") <= 500);
CREATE INDEX "IX_WhatsAppMessages_SenderUserId" ON "demorecruitment"."WhatsAppMessages" ("SenderUserId");
CREATE INDEX "IX_demorecruitment_WA_Msg_Cnv" ON "demorecruitment"."WhatsAppMessages" ("ConversationId", "CreatedAt" DESC);
CREATE INDEX "IX_WhatsAppMessages_ReplyToMessageId" ON "demorecruitment"."WhatsAppMessages" ("ReplyToMessageId");
CREATE UNIQUE INDEX "UQ_demorecruitment_WA_Msg_WamId" ON "demorecruitment"."WhatsAppMessages" ("WhatsAppMessageId") WHERE ("WhatsAppMessageId" IS NOT NULL);
CREATE INDEX "IX_demorecruitment_WA_Msg_Acc" ON "demorecruitment"."WhatsAppMessages" ("WhatsAppAccountId");
CREATE INDEX "IX_demorecruitment_WA_Msg_Status" ON "demorecruitment"."WhatsAppMessages" ("Status");
-- [platform].[SuperAdminUsers]
ALTER TABLE "platform"."SuperAdminUsers" ADD CONSTRAINT "UQ_SA_Email" UNIQUE NULLS NOT DISTINCT ("Email");
ALTER TABLE "platform"."SuperAdminUsers" ADD CONSTRAINT "LEN_SuperAdminUsers_FullName" CHECK (char_length("FullName") <= 200);
ALTER TABLE "platform"."SuperAdminUsers" ADD CONSTRAINT "LEN_SuperAdminUsers_Email" CHECK (char_length("Email") <= 255);
ALTER TABLE "platform"."SuperAdminUsers" ADD CONSTRAINT "LEN_SuperAdminUsers_PasswordHash" CHECK (char_length("PasswordHash") <= 500);
-- [platform].[Tenants]
ALTER TABLE "platform"."Tenants" ADD CONSTRAINT "UQ_Tenants_Subdomain" UNIQUE NULLS NOT DISTINCT ("Subdomain");
ALTER TABLE "platform"."Tenants" ADD CONSTRAINT "UQ_Tenants_Schema" UNIQUE NULLS NOT DISTINCT ("SchemaName");
ALTER TABLE "platform"."Tenants" ADD CONSTRAINT "CK_Tenants_Quota" CHECK ("StorageQuotaBytes">(0));
ALTER TABLE "platform"."Tenants" ADD CONSTRAINT "CK_Tenants_Storage" CHECK ("StorageUsedBytes">=(0));
ALTER TABLE "platform"."Tenants" ADD CONSTRAINT "CK_Tenants_SubStatus" CHECK ("SubscriptionStatus">=(1) AND "SubscriptionStatus"<=(5));
ALTER TABLE "platform"."Tenants" ADD CONSTRAINT "LEN_Tenants_CompanyName" CHECK (char_length("CompanyName") <= 200);
ALTER TABLE "platform"."Tenants" ADD CONSTRAINT "LEN_Tenants_SchemaName" CHECK (char_length("SchemaName") <= 100);
ALTER TABLE "platform"."Tenants" ADD CONSTRAINT "LEN_Tenants_Subdomain" CHECK (char_length("Subdomain") <= 100);
CREATE INDEX "IX_Tenants_Subdomain" ON "platform"."Tenants" ("Subdomain");
CREATE INDEX "IX_Tenants_SubStatus" ON "platform"."Tenants" ("SubscriptionStatus");

ALTER TABLE "_template"."Campaigns" ADD CONSTRAINT "FK_T_Camp_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."CandidateActivities" ADD CONSTRAINT "FK_T_CA_Cand" FOREIGN KEY ("CandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."CandidateActivities" ADD CONSTRAINT "FK_T_CA_CreBy" FOREIGN KEY ("CreatedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "FK_T_Cand_Branch" FOREIGN KEY ("BranchId") REFERENCES "_template"."Branches" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "FK_T_Cand_Pack" FOREIGN KEY ("JobPackageId") REFERENCES "_template"."JobPackages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "FK_T_Cand_RegBy" FOREIGN KEY ("RegisteredById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "FK_T_Cand_Sales" FOREIGN KEY ("AssignedSalesId") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "FK_T_Cand_Stage" FOREIGN KEY ("CurrentPackageStageId") REFERENCES "_template"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Candidates" ADD CONSTRAINT "FK_T_Candidates_Company" FOREIGN KEY ("CompanyId") REFERENCES "_template"."Companies" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."CandidateStageHistory" ADD CONSTRAINT "FK_T_CSH_By" FOREIGN KEY ("ChangedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."CandidateStageHistory" ADD CONSTRAINT "FK_T_CSH_Cand" FOREIGN KEY ("CandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."CandidateStageHistory" ADD CONSTRAINT "FK_T_CSH_FromStage" FOREIGN KEY ("FromStageId") REFERENCES "_template"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."CandidateStageHistory" ADD CONSTRAINT "FK_T_CSH_ToStage" FOREIGN KEY ("ToStageId") REFERENCES "_template"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Commissions" ADD CONSTRAINT "FK_T_Com_AppBy" FOREIGN KEY ("ApprovedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Commissions" ADD CONSTRAINT "FK_T_Com_Cand" FOREIGN KEY ("CandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Commissions" ADD CONSTRAINT "FK_T_Com_PaidBy" FOREIGN KEY ("PaidById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Commissions" ADD CONSTRAINT "FK_T_Com_Sales" FOREIGN KEY ("SalesUserId") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."CommissionTiers" ADD CONSTRAINT "FK_T_CT_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Companies" ADD CONSTRAINT "FK_T_Companies_User" FOREIGN KEY ("CreatedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."CompanyJobs" ADD CONSTRAINT "FK_T_CompanyJobs_Company" FOREIGN KEY ("CompanyId") REFERENCES "_template"."Companies" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "_template"."ContractUploads" ADD CONSTRAINT "FK_T_ContractUploads_Candidate" FOREIGN KEY ("MatchedCandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."ContractUploads" ADD CONSTRAINT "FK_T_ContractUploads_User" FOREIGN KEY ("UploadedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Documents" ADD CONSTRAINT "FK_T_Doc_Cand" FOREIGN KEY ("CandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Documents" ADD CONSTRAINT "FK_T_Doc_UpBy" FOREIGN KEY ("UploadedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."FollowUpReminders" ADD CONSTRAINT "FK_T_FUR_Assigned" FOREIGN KEY ("AssignedToId") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."FollowUpReminders" ADD CONSTRAINT "FK_T_FUR_Created" FOREIGN KEY ("CreatedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."FollowUpReminders" ADD CONSTRAINT "FK_T_FUR_Lead" FOREIGN KEY ("LeadId") REFERENCES "_template"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadActivities" ADD CONSTRAINT "FK_T_LA_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadActivities" ADD CONSTRAINT "FK_T_LA_Lead" FOREIGN KEY ("LeadId") REFERENCES "_template"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadCallLog" ADD CONSTRAINT "FK_T_LCL_By" FOREIGN KEY ("CalledById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadCallLog" ADD CONSTRAINT "FK_T_LCL_Lead" FOREIGN KEY ("LeadId") REFERENCES "_template"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadFunnelHistory" ADD CONSTRAINT "FK_T_LFH_By" FOREIGN KEY ("ChangedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadFunnelHistory" ADD CONSTRAINT "FK_T_LFH_Lead" FOREIGN KEY ("LeadId") REFERENCES "_template"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "FK_T_Ld_Branch" FOREIGN KEY ("BranchId") REFERENCES "_template"."Branches" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "FK_T_Ld_Campaign" FOREIGN KEY ("CampaignId") REFERENCES "_template"."Campaigns" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "FK_T_Ld_Duplicate" FOREIGN KEY ("DuplicateOfLeadId") REFERENCES "_template"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "FK_T_Ld_RegisteredBy" FOREIGN KEY ("RegisteredById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Leads" ADD CONSTRAINT "FK_T_Ld_Sales" FOREIGN KEY ("AssignedSalesId") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadVisits" ADD CONSTRAINT "FK_T_LV_Branch" FOREIGN KEY ("BranchId") REFERENCES "_template"."Branches" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadVisits" ADD CONSTRAINT "FK_T_LV_Lead" FOREIGN KEY ("LeadId") REFERENCES "_template"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadVisits" ADD CONSTRAINT "FK_T_LV_Package" FOREIGN KEY ("JobPackageId") REFERENCES "_template"."JobPackages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadVisits" ADD CONSTRAINT "FK_T_LV_Reception" FOREIGN KEY ("ReceptionUserId") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."LeadVisits" ADD CONSTRAINT "FK_T_LV_Sales" FOREIGN KEY ("AssignedSalesUserId") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Notifications" ADD CONSTRAINT "FK_T_Not_User" FOREIGN KEY ("UserId") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."PackageStages" ADD CONSTRAINT "FK_T_PS_Package" FOREIGN KEY ("PackageId") REFERENCES "_template"."JobPackages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."PackageStages" ADD CONSTRAINT "FK_T_PS_StageType" FOREIGN KEY ("StageTypeId") REFERENCES "_template"."StageTypes" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "_template"."PassportDownloadedCandidates" ADD CONSTRAINT "FK_T_PDC_Cand" FOREIGN KEY ("CandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."PassportDownloadedCandidates" ADD CONSTRAINT "FK_T_PDC_Log" FOREIGN KEY ("LogId") REFERENCES "_template"."PassportDownloadLogs" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."PassportDownloadLogs" ADD CONSTRAINT "FK_T_PDL_Package" FOREIGN KEY ("PackageId") REFERENCES "_template"."JobPackages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."PassportDownloadLogs" ADD CONSTRAINT "FK_T_PDL_User" FOREIGN KEY ("DownloadedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Payments" ADD CONSTRAINT "FK_T_Pay_Cand" FOREIGN KEY ("CandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Payments" ADD CONSTRAINT "FK_T_Pay_RecBy" FOREIGN KEY ("RecordedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."RefreshTokens" ADD CONSTRAINT "FK_T_RT_User" FOREIGN KEY ("UserId") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Refunds" ADD CONSTRAINT "FK_T_Ref_Cand" FOREIGN KEY ("CandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Refunds" ADD CONSTRAINT "FK_T_Ref_ExBy" FOREIGN KEY ("ExecutedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Refunds" ADD CONSTRAINT "FK_T_Ref_Pay" FOREIGN KEY ("RefundPaymentId") REFERENCES "_template"."Payments" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Refunds" ADD CONSTRAINT "FK_T_Ref_ReqBy" FOREIGN KEY ("RequestedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Refunds" ADD CONSTRAINT "FK_T_Ref_RevBy" FOREIGN KEY ("ReviewedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."SalaryPayments" ADD CONSTRAINT "FK_T_SP_ApprovedBy" FOREIGN KEY ("ApprovedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."SalaryPayments" ADD CONSTRAINT "FK_T_SP_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."SalaryPayments" ADD CONSTRAINT "FK_T_SP_PaidBy" FOREIGN KEY ("PaidById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."SalaryPayments" ADD CONSTRAINT "FK_T_SP_User" FOREIGN KEY ("UserId") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."StageActionCompletions" ADD CONSTRAINT "FK_T_SAC_Candidate" FOREIGN KEY ("CandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."StageActionCompletions" ADD CONSTRAINT "FK_T_SAC_Stage" FOREIGN KEY ("PackageStageId") REFERENCES "_template"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."StageActionCompletions" ADD CONSTRAINT "FK_T_SAC_User" FOREIGN KEY ("CompletedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."StageApprovalRequests" ADD CONSTRAINT "FK_T_SAR_Candidate" FOREIGN KEY ("CandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."StageApprovalRequests" ADD CONSTRAINT "FK_T_SAR_FromStage" FOREIGN KEY ("FromStageId") REFERENCES "_template"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."StageApprovalRequests" ADD CONSTRAINT "FK_T_SAR_ReqBy" FOREIGN KEY ("RequestedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."StageApprovalRequests" ADD CONSTRAINT "FK_T_SAR_RevBy" FOREIGN KEY ("ReviewedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."StageApprovalRequests" ADD CONSTRAINT "FK_T_SAR_ToStage" FOREIGN KEY ("ToStageId") REFERENCES "_template"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."Users" ADD CONSTRAINT "FK_T_Us_Br" FOREIGN KEY ("BranchId") REFERENCES "_template"."Branches" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."VisaUploads" ADD CONSTRAINT "FK_T_VisaUploads_Candidate" FOREIGN KEY ("MatchedCandidateId") REFERENCES "_template"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "_template"."VisaUploads" ADD CONSTRAINT "FK_T_VisaUploads_User" FOREIGN KEY ("UploadedById") REFERENCES "_template"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Campaigns" ADD CONSTRAINT "FK_demorecruitment_Ca_By" FOREIGN KEY ("CreatedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."CandidateActivities" ADD CONSTRAINT "FK_demo_CA_Cand" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."CandidateActivities" ADD CONSTRAINT "FK_demo_CA_CreBy" FOREIGN KEY ("CreatedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "FK_demo_Cand_Stage" FOREIGN KEY ("CurrentPackageStageId") REFERENCES "demorecruitment"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "FK_demorecruitment_Candidates_Company" FOREIGN KEY ("CompanyId") REFERENCES "demorecruitment"."Companies" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "FK_demorecruitment_Cnd_Br" FOREIGN KEY ("BranchId") REFERENCES "demorecruitment"."Branches" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "FK_demorecruitment_Cnd_JP" FOREIGN KEY ("JobPackageId") REFERENCES "demorecruitment"."JobPackages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "FK_demorecruitment_Cnd_Rg" FOREIGN KEY ("RegisteredById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Candidates" ADD CONSTRAINT "FK_demorecruitment_Cnd_Sa" FOREIGN KEY ("AssignedSalesId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."CandidateStageHistory" ADD CONSTRAINT "FK_demo_CSH_FromStage" FOREIGN KEY ("FromStageId") REFERENCES "demorecruitment"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."CandidateStageHistory" ADD CONSTRAINT "FK_demo_CSH_ToStage" FOREIGN KEY ("ToStageId") REFERENCES "demorecruitment"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."CandidateStageHistory" ADD CONSTRAINT "FK_demorecruitment_CSH_By" FOREIGN KEY ("ChangedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."CandidateStageHistory" ADD CONSTRAINT "FK_demorecruitment_CSH_Cnd" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Commissions" ADD CONSTRAINT "FK_demorecruitment_Com_ApBy" FOREIGN KEY ("ApprovedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Commissions" ADD CONSTRAINT "FK_demorecruitment_Com_Cnd" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Commissions" ADD CONSTRAINT "FK_demorecruitment_Com_PdBy" FOREIGN KEY ("PaidById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Commissions" ADD CONSTRAINT "FK_demorecruitment_Com_Sa" FOREIGN KEY ("SalesUserId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."CommissionTiers" ADD CONSTRAINT "FK_demorecruitment_CT_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Companies" ADD CONSTRAINT "FK_demorecruitment_Companies_User" FOREIGN KEY ("CreatedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."CompanyJobs" ADD CONSTRAINT "FK_demorecruitment_CompanyJobs_Company" FOREIGN KEY ("CompanyId") REFERENCES "demorecruitment"."Companies" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."ContractUploads" ADD CONSTRAINT "FK_demorecruitment_ContractUploads_Candidate" FOREIGN KEY ("MatchedCandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."ContractUploads" ADD CONSTRAINT "FK_demorecruitment_ContractUploads_User" FOREIGN KEY ("UploadedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."ConversationFollowUps" ADD CONSTRAINT "FK_demorecruitment_WA_FU_Assignee" FOREIGN KEY ("AssignedToId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."ConversationFollowUps" ADD CONSTRAINT "FK_demorecruitment_WA_FU_Cnv" FOREIGN KEY ("ConversationId") REFERENCES "demorecruitment"."WhatsAppConversations" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."ConversationFollowUps" ADD CONSTRAINT "FK_demorecruitment_WA_FU_CompletedBy" FOREIGN KEY ("CompletedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."ConversationFollowUps" ADD CONSTRAINT "FK_demorecruitment_WA_FU_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."ConversationNotes" ADD CONSTRAINT "FK_demorecruitment_WA_Note_Author" FOREIGN KEY ("AuthorId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."ConversationNotes" ADD CONSTRAINT "FK_demorecruitment_WA_Note_Cnv" FOREIGN KEY ("ConversationId") REFERENCES "demorecruitment"."WhatsAppConversations" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Documents" ADD CONSTRAINT "FK_demorecruitment_Doc_By" FOREIGN KEY ("UploadedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Documents" ADD CONSTRAINT "FK_demorecruitment_Doc_Cnd" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."FollowUpReminders" ADD CONSTRAINT "FK_demorecruitment_FUR_At" FOREIGN KEY ("AssignedToId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."FollowUpReminders" ADD CONSTRAINT "FK_demorecruitment_FUR_By" FOREIGN KEY ("CreatedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."FollowUpReminders" ADD CONSTRAINT "FK_demorecruitment_FUR_Ld" FOREIGN KEY ("LeadId") REFERENCES "demorecruitment"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."FollowUpReminders" ADD CONSTRAINT "FK_FollowUpReminders_Candidates" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadActivities" ADD CONSTRAINT "FK_demorecruitment_LA_By" FOREIGN KEY ("CreatedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadActivities" ADD CONSTRAINT "FK_demorecruitment_LA_Ld" FOREIGN KEY ("LeadId") REFERENCES "demorecruitment"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadCallLog" ADD CONSTRAINT "FK_demorecruitment_LCL_By" FOREIGN KEY ("CalledById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadCallLog" ADD CONSTRAINT "FK_demorecruitment_LCL_Ld" FOREIGN KEY ("LeadId") REFERENCES "demorecruitment"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadFunnelHistory" ADD CONSTRAINT "FK_demorecruitment_LFH_By" FOREIGN KEY ("ChangedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadFunnelHistory" ADD CONSTRAINT "FK_demorecruitment_LFH_Ld" FOREIGN KEY ("LeadId") REFERENCES "demorecruitment"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "FK__Leads__AssignedO__451F3D2B" FOREIGN KEY ("AssignedOfficeSalesId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "FK_demorecruitment_Ld_Br" FOREIGN KEY ("BranchId") REFERENCES "demorecruitment"."Branches" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "FK_demorecruitment_Ld_Ca" FOREIGN KEY ("CampaignId") REFERENCES "demorecruitment"."Campaigns" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "FK_demorecruitment_Ld_Rg" FOREIGN KEY ("RegisteredById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "FK_demorecruitment_Ld_Sa" FOREIGN KEY ("AssignedSalesId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "FK_demorecruitment_Ld_TeamMgr" FOREIGN KEY ("TeamManagerId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Leads" ADD CONSTRAINT "FK_Leads_GoogleSheet" FOREIGN KEY ("GoogleSheetId") REFERENCES "demorecruitment"."SalesGoogleSheets" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadVisits" ADD CONSTRAINT "FK_demorecruitment_LV_Br" FOREIGN KEY ("BranchId") REFERENCES "demorecruitment"."Branches" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadVisits" ADD CONSTRAINT "FK_demorecruitment_LV_JP" FOREIGN KEY ("JobPackageId") REFERENCES "demorecruitment"."JobPackages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadVisits" ADD CONSTRAINT "FK_demorecruitment_LV_Ld" FOREIGN KEY ("LeadId") REFERENCES "demorecruitment"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadVisits" ADD CONSTRAINT "FK_demorecruitment_LV_Re" FOREIGN KEY ("ReceptionUserId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."LeadVisits" ADD CONSTRAINT "FK_demorecruitment_LV_Sa" FOREIGN KEY ("AssignedSalesUserId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Notifications" ADD CONSTRAINT "FK_demorecruitment_Not_Us" FOREIGN KEY ("UserId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."PackageStages" ADD CONSTRAINT "FK_demo_PS_Package" FOREIGN KEY ("PackageId") REFERENCES "demorecruitment"."JobPackages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."PackageStages" ADD CONSTRAINT "FK_DR_PS_StageType" FOREIGN KEY ("StageTypeId") REFERENCES "demorecruitment"."StageTypes" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."PassportDownloadedCandidates" ADD CONSTRAINT "FK_PDC_Cand" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."PassportDownloadedCandidates" ADD CONSTRAINT "FK_PDC_Log" FOREIGN KEY ("LogId") REFERENCES "demorecruitment"."PassportDownloadLogs" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."PassportDownloadLogs" ADD CONSTRAINT "FK_PDL_Package" FOREIGN KEY ("PackageId") REFERENCES "demorecruitment"."JobPackages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."PassportDownloadLogs" ADD CONSTRAINT "FK_PDL_User" FOREIGN KEY ("DownloadedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Payments" ADD CONSTRAINT "FK_demorecruitment_Pay_ApprovedBy" FOREIGN KEY ("ApprovedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Payments" ADD CONSTRAINT "FK_demorecruitment_Pay_By" FOREIGN KEY ("RecordedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Payments" ADD CONSTRAINT "FK_demorecruitment_Pay_Cnd" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."RefreshTokens" ADD CONSTRAINT "FK_demorecruitment_RT_Us" FOREIGN KEY ("UserId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Refunds" ADD CONSTRAINT "FK_demorecruitment_Ref_Cnd" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Refunds" ADD CONSTRAINT "FK_demorecruitment_Ref_ExBy" FOREIGN KEY ("ExecutedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Refunds" ADD CONSTRAINT "FK_demorecruitment_Ref_Pay" FOREIGN KEY ("RefundPaymentId") REFERENCES "demorecruitment"."Payments" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Refunds" ADD CONSTRAINT "FK_demorecruitment_Ref_RqBy" FOREIGN KEY ("RequestedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Refunds" ADD CONSTRAINT "FK_demorecruitment_Ref_RvBy" FOREIGN KEY ("ReviewedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."SalaryPayments" ADD CONSTRAINT "FK_demorecruitment_SP_ApprovedBy" FOREIGN KEY ("ApprovedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."SalaryPayments" ADD CONSTRAINT "FK_demorecruitment_SP_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."SalaryPayments" ADD CONSTRAINT "FK_demorecruitment_SP_PaidBy" FOREIGN KEY ("PaidById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."SalaryPayments" ADD CONSTRAINT "FK_demorecruitment_SP_User" FOREIGN KEY ("UserId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."SalesGoogleSheets" ADD CONSTRAINT "FK_SalesGoogleSheets_Campaign" FOREIGN KEY ("CampaignId") REFERENCES "demorecruitment"."Campaigns" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."SalesGoogleSheets" ADD CONSTRAINT "FK_SalesGoogleSheets_CreatedBy" FOREIGN KEY ("CreatedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."SalesGoogleSheetUsers" ADD CONSTRAINT "FK_SheetUsers_Sheet" FOREIGN KEY ("SheetId") REFERENCES "demorecruitment"."SalesGoogleSheets" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."SalesGoogleSheetUsers" ADD CONSTRAINT "FK_SheetUsers_User" FOREIGN KEY ("SalesUserId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."StageActionCompletions" ADD CONSTRAINT "FK_SAC_Candidate" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."StageActionCompletions" ADD CONSTRAINT "FK_SAC_Stage" FOREIGN KEY ("PackageStageId") REFERENCES "demorecruitment"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."StageActionCompletions" ADD CONSTRAINT "FK_SAC_User" FOREIGN KEY ("CompletedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."StageApprovalRequests" ADD CONSTRAINT "FK_SAR_Candidate" FOREIGN KEY ("CandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."StageApprovalRequests" ADD CONSTRAINT "FK_SAR_FromStage" FOREIGN KEY ("FromStageId") REFERENCES "demorecruitment"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."StageApprovalRequests" ADD CONSTRAINT "FK_SAR_ReqBy" FOREIGN KEY ("RequestedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."StageApprovalRequests" ADD CONSTRAINT "FK_SAR_RevBy" FOREIGN KEY ("ReviewedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."StageApprovalRequests" ADD CONSTRAINT "FK_SAR_ToStage" FOREIGN KEY ("ToStageId") REFERENCES "demorecruitment"."PackageStages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."TeamLeadForms" ADD CONSTRAINT "FK_demorecruitment_TLF_Mgr" FOREIGN KEY ("ManagerId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Users" ADD CONSTRAINT "FK_demorecruitment_Us_Br" FOREIGN KEY ("BranchId") REFERENCES "demorecruitment"."Branches" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."Users" ADD CONSTRAINT "FK_demorecruitment_Us_Manager" FOREIGN KEY ("ManagerId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."VisaUploads" ADD CONSTRAINT "FK_VisaUploads_Candidate" FOREIGN KEY ("MatchedCandidateId") REFERENCES "demorecruitment"."Candidates" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."VisaUploads" ADD CONSTRAINT "FK_VisaUploads_User" FOREIGN KEY ("UploadedById") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppAccounts" ADD CONSTRAINT "FK_demorecruitment_WA_Acc_Agent" FOREIGN KEY ("AssignedSalesAgentId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppConversations" ADD CONSTRAINT "FK_demorecruitment_WA_Cnv_Acc" FOREIGN KEY ("WhatsAppAccountId") REFERENCES "demorecruitment"."WhatsAppAccounts" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppConversations" ADD CONSTRAINT "FK_demorecruitment_WA_Cnv_Agent" FOREIGN KEY ("AssignedSalesAgentId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppConversations" ADD CONSTRAINT "FK_demorecruitment_WA_Cnv_Cnt" FOREIGN KEY ("ContactId") REFERENCES "demorecruitment"."WhatsAppContacts" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppConversations" ADD CONSTRAINT "FK_demorecruitment_WA_Cnv_Lead" FOREIGN KEY ("LeadId") REFERENCES "demorecruitment"."Leads" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppHandoffs" ADD CONSTRAINT "FK_demorecruitment_WA_Hnd_Acc" FOREIGN KEY ("WhatsAppAccountId") REFERENCES "demorecruitment"."WhatsAppAccounts" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppHandoffs" ADD CONSTRAINT "FK_demorecruitment_WA_Hnd_Agent" FOREIGN KEY ("AssignedSalesAgentId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppHandoffs" ADD CONSTRAINT "FK_demorecruitment_WA_Hnd_Cnv" FOREIGN KEY ("ConversationId") REFERENCES "demorecruitment"."WhatsAppConversations" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppHandoffs" ADD CONSTRAINT "FK_demorecruitment_WA_Hnd_Lead" FOREIGN KEY ("LeadId") REFERENCES "demorecruitment"."Leads" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "FK_demorecruitment_WA_Msg_Acc" FOREIGN KEY ("WhatsAppAccountId") REFERENCES "demorecruitment"."WhatsAppAccounts" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "FK_demorecruitment_WA_Msg_Cnv" FOREIGN KEY ("ConversationId") REFERENCES "demorecruitment"."WhatsAppConversations" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "FK_demorecruitment_WA_Msg_Reply" FOREIGN KEY ("ReplyToMessageId") REFERENCES "demorecruitment"."WhatsAppMessages" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "demorecruitment"."WhatsAppMessages" ADD CONSTRAINT "FK_demorecruitment_WA_Msg_Sender" FOREIGN KEY ("SenderUserId") REFERENCES "demorecruitment"."Users" ("Id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "platform"."Tenants" ADD CONSTRAINT "FK_Tenants_SuperAdmin" FOREIGN KEY ("CreatedBySuperAdminId") REFERENCES "platform"."SuperAdminUsers" ("Id") ON DELETE NO ACTION ON UPDATE NO ACTION;
